[functions.rh-enviar-nomina-whatsapp]
verify_jwt = false

[functions.contactar-proveedor]
verify_jwt = false

[functions.checador-sync]
verify_jwt = false

[functions.skill-enviar-minuta]
verify_jwt = true
