(function(){
'use strict';
const $=id=>document.getElementById(id),text=v=>String(v??'').trim(),lower=v=>text(v).toLocaleLowerCase('es-MX'),num=v=>Number(v)||0;
const esc=v=>text(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const money=v=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(num(v));
const date=v=>v?new Date(`${v}T12:00:00`).toLocaleDateString('es-MX'):'Sin fecha';
let rows=[],groups=[],editing=null,draft=[];
function badge(s){return({no_revisada:'<span class="profile-badge warning">No revisada</span>',en_compra:'<span class="profile-badge info">En compra</span>',comprado:'<span class="profile-badge success">Comprada</span>',no_viable:'<span class="profile-badge danger">No viable</span>',cancelado:'<span class="profile-badge">Cancelada</span>'})[s]||'<span class="profile-badge">Sin estado</span>'}
function makeGroups(){const map=new Map();rows.forEach(r=>{const key=r.folio||`ST-${r.id}`;if(!map.has(key))map.set(key,{folio:key,items:[],estado:r.estado,prioridad:r.prioridad,fechaRequerida:r.fechaRequerida,solicitadoPor:r.solicitadoPor,responsableCompra:r.responsableCompra,motivoNoViable:r.motivoNoViable,notas:r.notas});map.get(key).items.push(r)});groups=[...map.values()].sort((a,b)=>String(b.folio).localeCompare(String(a.folio)))}
function filtered(){const q=lower($('search').value),s=$('state').value,p=$('priority').value;return groups.filter(g=>(!q||(window.SkilledSearch?.matches?window.SkilledSearch.matches([g.folio,g.solicitadoPor,g.responsableCompra,...g.items.flatMap(i=>[i.negocio,i.producto,i.marcaEspecifica])],q):lower([g.folio,g.solicitadoPor,g.responsableCompra,...g.items.flatMap(i=>[i.negocio,i.producto,i.marcaEspecifica])].join(' ')).includes(q)))&&(!s||g.estado===s)&&(!p||g.prioridad===p))}
function render(){makeGroups();const data=filtered();$('m-new').textContent=groups.filter(g=>g.estado==='no_revisada').length;$('m-buying').textContent=groups.filter(g=>g.estado==='en_compra').length;$('m-done').textContent=groups.filter(g=>g.estado==='comprado').length;$('m-cost').textContent=money(groups.filter(g=>!['comprado','cancelado','no_viable'].includes(g.estado)).flatMap(g=>g.items).reduce((s,r)=>s+num(r.costoEstimado),0));$('lists').innerHTML=data.length?data.map(g=>{const total=g.items.reduce((s,i)=>s+num(i.costoEstimado),0),businesses=[...new Set(g.items.map(i=>i.negocio).filter(Boolean))];return `<article class="profile-card overflow-hidden"><div class="p-5"><div class="flex items-start justify-between gap-4"><div><div class="flex flex-wrap items-center gap-2"><span class="font-mono text-[10px] font-bold text-sky-300">${esc(g.folio)}</span>${badge(g.estado)}${g.prioridad==='urgente'?'<span class="profile-badge danger">Urgente</span>':''}</div><h2 class="mt-3 text-lg font-bold text-white">${g.items.length} artículo${g.items.length===1?'':'s'} por comprar</h2><p class="mt-1 text-xs text-gray-500">${esc(businesses.join(' · ')||'Negocio por definir')} · Requerido ${date(g.fechaRequerida)}</p></div><div class="text-right"><p class="text-[9px] uppercase tracking-widest text-gray-500">Estimado</p><p class="mt-1 text-xl font-bold text-emerald-300">${money(total)}</p></div></div><div class="mt-4 space-y-2">${g.items.slice(0,4).map(i=>`<div class="flex items-center justify-between gap-3 rounded-xl border border-[#1a2944] bg-[#0b1222] px-3 py-2"><div class="min-w-0"><p class="truncate text-xs font-semibold text-white">${esc(i.producto)}</p><p class="mt-1 truncate text-[9px] text-gray-500">${esc(i.negocio)} · ${esc(i.marcaEspecifica||'Sin marca específica')}</p></div><strong class="text-xs text-gray-200">${i.cantidad} ${esc(i.unidad)}</strong></div>`).join('')}${g.items.length>4?`<p class="text-[10px] text-sky-300">+ ${g.items.length-4} artículos adicionales</p>`:''}</div></div><div class="border-t border-[#1a2944] px-5 py-3 flex items-center justify-between"><p class="text-[10px] text-gray-500">Solicita: ${esc(g.solicitadoPor||'No indicado')}</p><button class="profile-action-button primary" data-edit-list="${esc(g.folio)}">Abrir lista</button></div></article>`}).join(''):'<div class="profile-card profile-empty xl:col-span-2"><div><div class="profile-empty-icon">⌕</div><p class="profile-empty-title">Sin listas</p><p class="profile-empty-copy">No hay listas de compra con los filtros actuales.</p></div></div>'}
function renderDraft(){const total=draft.reduce((s,i)=>s+num(i.costoEstimado),0);$('item-count').textContent=`${draft.length} artículo${draft.length===1?'':'s'}`;$('list-total').textContent=money(total);$('items-body').innerHTML=draft.length?draft.map((i,index)=>`<tr><td>${index+1}</td><td>${esc(i.negocio)}</td><td><p class="font-semibold text-white">${esc(i.producto)}</p></td><td>${esc([i.marcaEspecifica,i.presentacion].filter(Boolean).join(' · ')||'—')}</td><td>${i.cantidad} ${esc(i.unidad)}</td><td class="font-bold text-emerald-300">${money(i.costoEstimado)}</td><td class="text-right"><button class="profile-action-button text-rose-300" data-remove-item="${index}">Quitar</button></td></tr>`).join(''):'<tr><td colspan="7" class="py-10 text-center text-gray-500">Agrega el primer artículo.</td></tr>'}
function addItem(){const item={negocio:text($('business').value),producto:text($('product').value),marcaEspecifica:text($('brand').value),presentacion:'',cantidad:Math.max(.01,num($('quantity').value)||1),unidad:text($('unit').value)||'pieza',costoEstimado:Math.max(0,num($('cost').value))};if(!item.negocio||!item.producto)return alert('Captura el negocio y el producto.');draft.push(item);['product','brand','cost'].forEach(id=>$(id).value='');$('quantity').value=1;$('product').focus();renderDraft()}
function open(group=null){editing=group;draft=group?group.items.map(i=>({...i})):[];$('modal-title').textContent=group?'Editar lista de compra':'Nueva lista de compra';$('requested-by').value=group?.solicitadoPor||'';$('buyer').value=group?.responsableCompra||'';$('required').value=group?.fechaRequerida||'';$('item-priority').value=group?.prioridad||'normal';$('item-state').value=group?.estado||'no_revisada';$('not-viable').value=group?.motivoNoViable||'';$('notes').value=group?.notas||'';$('business').value='';$('product').value='';$('brand').value='';$('quantity').value=1;$('unit').value='pieza';$('cost').value='';$('delete-list').classList.toggle('hidden',!group);renderDraft();$('modal').classList.remove('hidden');$('modal').classList.add('flex')}
function close(){$('modal').classList.add('hidden');$('modal').classList.remove('flex');editing=null;draft=[]}
async function save(){if(!draft.length)return alert('Agrega al menos un artículo.');const state=$('item-state').value,motive=text($('not-viable').value);if(state==='no_viable'&&!motive)return alert('Captura el motivo por el que la compra no es viable.');const b=$('save');b.disabled=true;try{const folio=editing?.folio||`ST-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${String(Date.now()).slice(-6)}`;if(editing){const existingIds=new Set(draft.map(i=>Number(i.id)).filter(Boolean));for(const old of editing.items)if(!existingIds.has(Number(old.id)))await SkilledDB.deleteStoreRequest(old.id)}for(const item of draft)await SkilledDB.saveStoreRequest({id:item.id,folio,negocio:item.negocio,producto:item.producto,marcaEspecifica:item.marcaEspecifica,presentacion:item.presentacion,cantidad:item.cantidad,unidad:item.unidad,costoEstimado:item.costoEstimado,fechaRequerida:$('required').value,prioridad:$('item-priority').value,estado:state,solicitadoPor:$('requested-by').value,responsableCompra:$('buyer').value,motivoNoViable:motive,notas:$('notes').value});close();await load()}catch(e){alert(e.message)}finally{b.disabled=false}}
async function removeList(){if(!editing||!confirm(`¿Eliminar la lista ${editing.folio} y sus ${editing.items.length} artículos?`))return;try{for(const item of editing.items)await SkilledDB.deleteStoreRequest(item.id);close();await load()}catch(e){alert(e.message)}}
async function load(){try{rows=await SkilledDB.listStoreRequests();render()}catch(e){$('lists').innerHTML=`<div class="profile-card profile-empty xl:col-span-2"><p class="text-rose-300">${esc(e.message)}. Ejecuta SQL_MAESTRO_CRM.sql.</p></div>`}}
$('new').addEventListener('click',()=>open());$('refresh').addEventListener('click',load);$('lists').addEventListener('click',e=>{const b=e.target.closest('[data-edit-list]');if(b)open(groups.find(g=>g.folio===b.dataset.editList))});$('add-item').addEventListener('click',addItem);$('items-body').addEventListener('click',e=>{const b=e.target.closest('[data-remove-item]');if(b){draft.splice(Number(b.dataset.removeItem),1);renderDraft()}});['search','state','priority'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));$('global-search').addEventListener('input',e=>{$('search').value=e.target.value;render()});$('close').addEventListener('click',close);$('cancel').addEventListener('click',close);$('save').addEventListener('click',save);$('delete-list').addEventListener('click',removeList);$('modal').addEventListener('click',e=>{if(e.target===$('modal'))close()});load();
})();