const STATIC_CACHE='skilled-crm-static-v39';
const PAGE_CACHE='skilled-crm-pages-v39';
const CORE=['./interfaz.css?v=39','./navegacion-suave.js?v=39','./skilled-performance.js?v=39','./skilled-sidebar.js?v=39','./skilled-search.js?v=39','./skilled-supabase.js?v=39','./auth-guard.js?v=39','./favicon-32x32.png?v=29','./favicon-192x192.png?v=29'];
self.addEventListener('install',event=>{event.waitUntil((async()=>{const cache=await caches.open(STATIC_CACHE);await Promise.all(CORE.map(async url=>{try{const response=await fetch(url,{cache:'reload'});if(response.ok)await cache.put(url,response)}catch(_){}}));await self.skipWaiting()})())});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>key.startsWith('skilled-crm-')&&![STATIC_CACHE,PAGE_CACHE].includes(key)).map(key=>caches.delete(key)));await self.clients.claim()})())});
function cacheable(response){return response&&(response.ok||response.type==='opaque')}
const PAGE_REFRESH=new Map();
const PAGE_REFRESH_MS=180000;
async function pageFast(request){const cache=await caches.open(PAGE_CACHE);const cached=await cache.match(request,{ignoreSearch:false});const key=request.url,now=Date.now(),last=PAGE_REFRESH.get(key)||0;if(cached){if(now-last>PAGE_REFRESH_MS){PAGE_REFRESH.set(key,now);fetch(request).then(response=>{if(cacheable(response))cache.put(request,response.clone()).catch(()=>{})}).catch(()=>{})}return cached}try{const response=await fetch(request);if(cacheable(response))cache.put(request,response.clone()).catch(()=>{});PAGE_REFRESH.set(key,now);return response}catch(_){return Response.error()}}
async function cacheFirst(request,cacheName){const cache=await caches.open(cacheName);const cached=await cache.match(request,{ignoreSearch:false});if(cached)return cached;try{const response=await fetch(request);if(cacheable(response))cache.put(request,response.clone()).catch(()=>{});return response}catch(_){return Response.error()}}
async function staleWhileRevalidate(request,cacheName=STATIC_CACHE){const cache=await caches.open(cacheName);const cached=await cache.match(request,{ignoreSearch:false});const fresh=fetch(request).then(response=>{if(cacheable(response))cache.put(request,response.clone()).catch(()=>{});return response}).catch(()=>null);return cached||await fresh||Response.error()}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(/\/rest\/v1\/|\/auth\/v1\/|\/functions\/v1\/|\/realtime\/v1\//.test(url.pathname))return;const sameOrigin=url.origin===self.location.origin;if(request.mode==='navigate'&&sameOrigin){event.respondWith(pageFast(request));return}if(sameOrigin&&/\.html?$/i.test(url.pathname)){event.respondWith(pageFast(request));return}const staticFile=/\.(?:js|css|png|jpg|jpeg|webp|gif|svg|ico|woff2?|xlsx)(?:$|\?)/i.test(url.pathname+url.search);const trustedCdn=/^(cdn\.jsdelivr\.net|cdnjs\.cloudflare\.com|cdn\.tailwindcss\.com|fonts\.googleapis\.com|fonts\.gstatic\.com)$/i.test(url.hostname);if(sameOrigin&&staticFile){event.respondWith(cacheFirst(request,STATIC_CACHE));return}if(trustedCdn)event.respondWith(cacheFirst(request,STATIC_CACHE))});
