(function(){
'use strict';
const root=document.documentElement;
const RELEASE='83';
const connection=navigator.connection||navigator.mozConnection||navigator.webkitConnection;
function addConnectionHints(){
 const hints=[['preconnect','https://cdn.jsdelivr.net','anonymous'],['dns-prefetch','https://cdn.jsdelivr.net',''],['preconnect','https://cuxnzqbszzrfnrinxbdp.supabase.co','anonymous'],['dns-prefetch','https://cuxnzqbszzrfnrinxbdp.supabase.co','']];
 hints.forEach(([rel,href,crossorigin])=>{if(document.head.querySelector(`link[rel="${rel}"][href="${href}"]`))return;const link=document.createElement('link');link.rel=rel;link.href=href;if(crossorigin)link.crossOrigin=crossorigin;document.head.appendChild(link)});
}
addConnectionHints();
async function cleanupOldRelease(){try{if(localStorage.getItem('skilled_crm_release')===RELEASE)return;if('caches'in window){const keys=await caches.keys();await Promise.all(keys.filter(key=>key.startsWith('skilled-crm-')).map(key=>caches.delete(key)))}localStorage.setItem('skilled_crm_release',RELEASE)}catch(_){}}
function currentFile(){let file=(location.pathname.split('/').pop()||'').toLowerCase();if(file&&!/\.html?$/.test(file))file+='.html';return file}
function cachedRole(){try{return String(JSON.parse(localStorage.getItem('skilled_profile_cache')||'null')?.rol||'').toLowerCase()}catch(_){return''}}
function themeProfile(){const requested=String(new URLSearchParams(location.search).get('perfil')||'').toLowerCase();if(['administrador','jefe_almacen','almacen','compras','proyectos','planeacion','coordinacion','logistica','recepcion','rh','finanzas','gerente_general','subgerente','tsi','sky_demo','consulta'].includes(requested))return requested;const file=currentFile();if(file.startsWith('co.'))return'compras';if(file.startsWith('rh.'))return'rh';if(file.startsWith('fi.'))return'finanzas';if(file.startsWith('pl.'))return'planeacion';if(file.startsWith('cr.'))return'coordinacion';if(file.startsWith('lg.'))return'logistica';if(file.startsWith('re.'))return'recepcion';if(file.startsWith('gg.'))return'gerente_general';if(file.startsWith('sg.'))return'subgerente';if(file.startsWith('sky.'))return'sky_demo';if(file.startsWith('tsi.'))return'tsi';if(file.startsWith('al.'))return'almacen';const remembered=sessionStorage.getItem('skilled_active_profile');if(['administrador','jefe_almacen','almacen','compras','proyectos','planeacion','coordinacion','logistica','recepcion','rh','finanzas','gerente_general','subgerente','tsi','sky_demo','consulta'].includes(remembered))return remembered;const role=cachedRole();if(['administrador','jefe_almacen','almacen','compras','proyectos','planeacion','coordinacion','logistica','recepcion','rh','finanzas','gerente_general','subgerente','tsi','sky_demo','consulta'].includes(role))return role;return'almacen'}
const themeStorageKey=()=>`skilled_tema_${themeProfile()}`;
window.SkilledThemeKey=themeStorageKey();
function applySidebarStateImmediately(){const profile=themeProfile();const compact=localStorage.getItem(`skilled_sidebar_compact_${profile}`)==='1';root.dataset.crmSidebarProfile=profile;root.dataset.crmSidebarCompact=compact?'1':'0'}
function applyThemeImmediately(){if(currentFile()!=='login.html'&&window.SkilledTheme?.applyStored){window.SkilledTheme.applyStored();return}const light=currentFile()!=='login.html'&&localStorage.getItem(themeStorageKey())==='claro';const background=light?'#f2f4f9':'#060814';root.dataset.crmTheme=light?'claro':'oscuro';root.classList.toggle('tema-claro',light);root.style.backgroundColor=background;root.style.colorScheme=light?'light':'dark';if(document.body){document.body.classList.toggle('tema-claro',light);document.body.style.backgroundColor=background}}
applyThemeImmediately();applySidebarStateImmediately();root.dataset.skyAllowed=['administrador','jefe_almacen','almacen','compras','proyectos','planeacion','coordinacion','logistica','recepcion','rh','finanzas','gerente_general','subgerente','tsi','sky_demo','consulta'].includes(themeProfile())?'1':'0';if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',applyThemeImmediately,{once:true});
function ensureProgressBar(){let bar=document.getElementById('crm-route-progress');if(bar)return bar;bar=document.createElement('div');bar.id='crm-route-progress';bar.setAttribute('aria-hidden','true');root.appendChild(bar);return bar}
let progressSafetyTimer=0;
function beginProgress(){const bar=ensureProgressBar();bar.classList.remove('is-finishing');bar.classList.add('is-active');root.classList.add('crm-route-pending');clearTimeout(progressSafetyTimer);progressSafetyTimer=setTimeout(finishProgress,1600)}
function finishProgress(){root.classList.remove('crm-route-pending');const bar=document.getElementById('crm-route-progress');if(!bar)return;bar.classList.add('is-finishing');setTimeout(()=>bar.remove(),140)}
window.addEventListener('pageshow',finishProgress);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',finishProgress,{once:true});else finishProgress();
function useCleanRoutes(){const host=location.hostname.toLowerCase();return host.endsWith('.pages.dev')||host.endsWith('.skilledmx.cloud')}
function optimizeRoute(url){if(!url||!useCleanRoutes())return url;if(/\.html?$/i.test(url.pathname)){const next=new URL(url.href);next.pathname=next.pathname.replace(/\.html?$/i,'');return next}return url}
function targetUrl(anchor){if(!anchor||anchor.hasAttribute('download')||anchor.hasAttribute('data-no-transition'))return null;if(/cerrar\s+sesi/i.test(anchor.textContent||''))return null;if(anchor.target&&anchor.target.toLowerCase()!=='_self')return null;const raw=anchor.getAttribute('href')||'';if(!raw||raw.startsWith('#')||raw.startsWith('javascript:')||raw.startsWith('mailto:')||raw.startsWith('tel:'))return null;let url;try{url=new URL(raw,location.href)}catch(_){return null}if(url.origin!==location.origin)return null;if(url.pathname===location.pathname&&url.search===location.search&&!url.hash)return null;if(!/\.(?:html?)$/i.test(url.pathname)&&!url.pathname.endsWith('/'))return null;const optimized=optimizeRoute(url);if(optimized.pathname===location.pathname&&optimized.search===location.search&&!optimized.hash)return null;return optimized}
const prefetched=new Map();
function fastConnection(){return !(connection?.saveData||['slow-2g','2g'].includes(connection?.effectiveType))}
function prefetch(anchor,aggressive=false){if(!fastConnection())return;const url=targetUrl(anchor);if(!url||prefetched.has(url.href))return;const link=document.createElement('link');link.rel='prefetch';link.as='document';link.href=url.href;link.fetchPriority=aggressive?'high':'low';document.head.appendChild(link);prefetched.set(url.href,link);if(prefetched.size>10){const first=prefetched.keys().next().value;prefetched.get(first)?.remove();prefetched.delete(first)}}
window.SkilledNavigationPrefetch=href=>{try{const anchor=document.createElement('a');anchor.href=String(href||'');prefetch(anchor,false)}catch(_){}};
let hoverTimer=0;
document.addEventListener('pointerover',event=>{const anchor=event.target.closest?.('a[href]');if(!anchor)return;clearTimeout(hoverTimer);hoverTimer=setTimeout(()=>prefetch(anchor,false),110)},{passive:true,capture:true});
document.addEventListener('focusin',event=>{const anchor=event.target.closest?.('a[href]');if(anchor)prefetch(anchor,false)},true);
document.addEventListener('pointerdown',event=>{const anchor=event.target.closest?.('a[href]');if(anchor)prefetch(anchor,true)},{passive:true,capture:true});
document.addEventListener('click',event=>{if(event.defaultPrevented||event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;const anchor=event.target.closest?.('a[href]');const target=targetUrl(anchor);if(!target)return;beginProgress();let original=null;try{original=new URL(anchor.getAttribute('href')||'',location.href)}catch(_){}if(original&&target.href!==original.href){event.preventDefault();location.assign(target.href)}},false);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',cleanupOldRelease,{once:true});else cleanupOldRelease();
async function enableServiceWorker(){if(!('serviceWorker'in navigator))return;if(!window.isSecureContext&&!['localhost','127.0.0.1'].includes(location.hostname))return;try{const registration=await navigator.serviceWorker.register('./crm-sw.js?v=83',{scope:'./',updateViaCache:'none'});const update=()=>registration.update().catch(()=>{});if('requestIdleCallback'in window)requestIdleCallback(update,{timeout:3000});else setTimeout(update,1800)}catch(_){}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enableServiceWorker,{once:true});else enableServiceWorker();
})();
