(function(){
'use strict';
const state={errors:new Map(),warnings:new Map(),lastHealth:null};
const text=v=>String(v??'').trim();
const esc=v=>text(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function normalize(error,label=''){const code=text(error?.code||error?.status||'');const raw=text(error?.message||error?.details||error||'Error desconocido');let title='No se pudo consultar RH';let action='Vuelve a intentar. Si persiste, usa el diagnóstico de RH.';if(code==='42501'||/permission denied|row.level.security|rls|not allowed|unauthorized|forbidden/i.test(raw)){title='Permiso de RH rechazado';action='Verifica que la cuenta tenga rol RH activo y que las políticas RLS estén instaladas.'}else if(code==='42P01'||code==='PGRST205'||/does not exist|could not find the table|schema cache/i.test(raw)){title='Falta una tabla de RH';action='Ejecuta SQL_MAESTRO_CRM.sql de esta versión y vuelve a cargar.'}else if(code==='42703'||/column .* does not exist|could not find the .* column/i.test(raw)){title='Esquema de RH desactualizado';action='Ejecuta SQL_MAESTRO_CRM.sql de esta versión para agregar las columnas faltantes.'}else if(code==='PGRST202'||/could not find the function|function .* does not exist/i.test(raw)){title='Función de RH no instalada';action='Ejecuta SQL_MAESTRO_CRM.sql de esta versión para instalar las RPC necesarias.'}else if(/failed to fetch|networkerror|network request|load failed|timeout|timed out|abort/i.test(raw)){title='Sin conexión con Supabase';action='Comprueba Internet y vuelve a intentar; los datos no se marcarán como vacíos mientras exista este error.'}return{label:text(label),code,raw,title,action,message:`${label?label+': ':''}${raw}`}}
function ensureBanner(){let el=document.getElementById('rh-runtime-status');if(el)return el;el=document.createElement('section');el.id='rh-runtime-status';el.className='hidden';el.style.cssText='position:fixed;z-index:2147483000;left:50%;top:94px;transform:translateX(-50%);width:min(760px,calc(100vw - 28px));border:1px solid rgba(245,158,11,.38);background:rgba(27,18,4,.97);box-shadow:0 18px 55px rgba(0,0,0,.42);border-radius:14px;padding:12px 14px;color:#fde68a;font:600 12px/1.45 Inter,system-ui,sans-serif';document.body.appendChild(el);return el}
function render(){const el=ensureBanner();const errors=[...state.errors.values()];const warnings=[...state.warnings.values()];if(!errors.length&&!warnings.length){el.classList.add('hidden');el.innerHTML='';return}el.classList.remove('hidden');const first=errors[0]||warnings[0];const details=errors.length>1?` · ${errors.length} consultas con error`:'';el.innerHTML=`<div style="display:flex;gap:12px;align-items:flex-start"><div style="flex:1;min-width:0"><div style="font-size:12px;color:${errors.length?'#fecaca':'#fde68a'}">${esc(first.title||'Aviso de RH')}${esc(details)}</div><div style="margin-top:3px;font-size:11px;font-weight:500;color:#d1d5db;word-break:break-word">${esc(first.message||first.raw||'')}</div><div style="margin-top:4px;font-size:10px;font-weight:500;color:#94a3b8">${esc(first.action||'')}</div></div><button type="button" data-rh-status-close style="border:1px solid #334155;border-radius:9px;background:#111827;color:#cbd5e1;padding:5px 8px;cursor:pointer">Cerrar</button></div>`;el.querySelector('[data-rh-status-close]')?.addEventListener('click',()=>el.classList.add('hidden'))}
function report(label,error){const info=normalize(error,label);state.errors.set(text(label)||`error-${Date.now()}`,info);render();console.error('[RH]',label,error);return info}
function warn(label,message,action=''){state.warnings.set(text(label)||`warning-${Date.now()}`,{title:'Aviso de RH',message:text(message),action:text(action),raw:text(message)});render()}
function clear(label){if(label){state.errors.delete(text(label));state.warnings.delete(text(label))}else{state.errors.clear();state.warnings.clear()}render()}
async function ready(timeout=9000){const start=Date.now();while(Date.now()-start<timeout){if(window.SkilledDB?.client)return true;await sleep(80)}throw new Error('La conexión de Supabase no terminó de iniciar.')}
async function query(label,factory,{required=false}={}){try{await ready();const result=await factory();if(result?.error){const info=report(label,result.error);if(required)throw Object.assign(new Error(info.message),{cause:result.error,rhInfo:info});return{ok:false,data:null,error:result.error,info}}state.errors.delete(text(label));render();return{ok:true,data:result?.data??null,error:null,count:result?.count??null,result}}catch(error){const info=error?.rhInfo||report(label,error);if(required)throw error;return{ok:false,data:null,error,info}}
}
async function profile(){try{await ready();return await SkilledDB.getMyProfile()}catch(error){report('Perfil de usuario',error);throw error}}
async function health(){await ready();const resources=[['Personal','rh_personal'],['Proyectos','proyectos'],['Asignaciones','rh_proyecto_asignaciones'],['Incidencias','rh_incidencias'],['Documentos','rh_documentos'],['Capacitación','rh_capacitaciones'],['Participantes','rh_capacitacion_participantes'],['Nómina','rh_nomina_periodos'],['Detalle de nómina','rh_nomina_detalles'],['Envíos de nómina','rh_nomina_envios'],['Configuración de nómina','rh_nomina_configuracion'],['Activos','rh_activos_oficina'],['Resguardos','rh_activos_asignaciones']];const results=[];let p=null,server=null;try{p=await SkilledDB.getMyProfile()}catch(error){results.push({name:'Perfil',ok:false,error:normalize(error,'Perfil')})}try{const rpc=await SkilledDB.client.rpc('rh_diagnostico_v72');if(!rpc?.error)server=rpc?.data||null;else if(!['PGRST202','42883'].includes(text(rpc.error?.code)))results.push({name:'Diagnóstico servidor',ok:false,error:normalize(rpc.error,'Diagnóstico servidor')})}catch(_){}for(const [name,table] of resources){const r=await query(`Diagnóstico ${name}`,()=>SkilledDB.client.from(table).select('id',{count:'exact',head:true}));results.push({name,table,ok:r.ok,count:r.count,error:r.info||null});if(r.ok)clear(`Diagnóstico ${name}`)}state.lastHealth={at:new Date().toISOString(),profile:p,server,results};return state.lastHealth}
function diagnosticText(result=state.lastHealth){if(!result)return'Sin diagnóstico ejecutado.';const role=text(result.profile?.rol||result.profile?.role||'—');const rows=result.results.map(r=>`${r.ok?'OK':'ERROR'} · ${r.name}${r.ok&&Number.isFinite(r.count)?` (${r.count})`:''}${r.error?.code?` · ${r.error.code}`:''}${r.error?.raw?` · ${r.error.raw}`:''}`);return[`Rol: ${role}`,...rows].join('\n')}
function addDiagnosticButton(){if(document.getElementById('rh-diagnostic-button'))return;const btn=document.createElement('button');btn.id='rh-diagnostic-button';btn.type='button';btn.textContent='Diagnóstico RH';btn.style.cssText='position:fixed;right:18px;bottom:18px;z-index:2147482000;border:1px solid #1d4ed8;border-radius:11px;background:#0b1733;color:#bfdbfe;padding:8px 11px;font:700 10px Inter,system-ui,sans-serif;box-shadow:0 10px 30px rgba(0,0,0,.3);cursor:pointer;opacity:.84';btn.addEventListener('click',async()=>{btn.disabled=true;const old=btn.textContent;btn.textContent='Revisando…';try{const result=await health();const failed=result.results.filter(r=>!r.ok);if(!failed.length){clear();alert(`Diagnóstico RH correcto.\nRol: ${text(result.profile?.rol||'—')}\nLas tablas principales responden.`)}else alert(`Diagnóstico RH detectó ${failed.length} problema(s):\n\n${diagnosticText(result)}`)}catch(error){alert(`No se pudo completar el diagnóstico RH:\n${text(error?.message||error)}`)}finally{btn.disabled=false;btn.textContent=old}});document.body.appendChild(btn)}
window.RHCore={state,text,escape:esc,normalize,report,warn,clear,ready,query,profile,health,diagnosticText,addDiagnosticButton};
window.addEventListener('unhandledrejection',event=>{const reason=event.reason;if(reason&&(/supabase|postgrest|rh_|permission|schema|fetch/i.test(text(reason?.message||reason))))report('Error no controlado',reason)});
window.addEventListener('DOMContentLoaded',()=>{setTimeout(addDiagnosticButton,300)},{once:true});
})();
