(function(){
'use strict';
const STOP=new Set('a al algo ante bajo cada como con contra cual cuales cuando cuanto cuantos cuanta cuantas de del desde donde el ella en entre es ese esa esos esas esta este esto estoy hay la las le lo los me mi para por que se sin sobre soy su sus un una unos unas y o u buscar busca buscame buscarme muestra muestrame mostrar ver quiero necesito dame checa checame revisa revisame encuentra encontrar dime saber saberme tengo tenemos existe existen registrado registrada registrados registradas quisiera favor puedes podrias podria'.split(' '));
const GROUPS=[['pija','pijas','tornillo','tornillos','autotaladrante','autotaladrantes','autorroscante','autorroscantes','tornilleria','tornillería'],['tubo','tubos','tuberia','tuberías','conduit','caño','caños'],['cincho','cinchos','cintillo','cintillos','tyrap','tyraps','tie','wrap','sujetacables'],['desarmador','desarmadores','destornillador','destornilladores'],['esmeril','esmeriles','amoladora','amoladoras'],['montacargas','forklift'],['camioneta','pickup','troca','pick up'],['automovil','automóvil','auto','carro','coche','vehiculo','vehículo'],['cable','cables','conductor','conductores'],['contacto','tomacorriente','receptaculo','receptáculo'],['apagador','interruptor'],['foco','lampara','lámpara','luminaria'],['cople','copla','union','unión'],['abrazadera','abrazaderas','grapa','grapas'],['rondana','rondanas','arandela','arandelas'],['tuerca','tuercas','nut'],['broca','brocas','mecha','mechas'],['casco','cascos','yelmo'],['lentes','gafas','anteojos'],['bota','botas','calzado'],['almacen','almacén','almacenes','bodega','bodegas'],['herramienta','herramientas','hta','tool'],['orden','ordenes','órdenes','oc','po'],['proyecto','proyectos','proy','obra','obras'],['proveedor','proveedores','prov'],['cotizacion','cotización','cotizaciones','cotiza','cotizar'],['requisicion','requisición','requisiciones','solicitud','solicitudes'],['correo','email','mail'],['telefono','teléfono','telefonos','teléfonos','celular','celulares','whatsapp','wa'],['trabajador','trabajadores','empleado','empleados','colaborador','colaboradores','personal'],['entrada','entradas','ingreso','ingresos'],['salida','salidas','entrega','entregas'],['disponible','disponibles','libre','libres'],['asignado','asignada','asignados','asignadas'],['mantenimiento','reparacion','reparación','taller'],['activo','activa','activos','activas'],['inactivo','inactiva','inactivos','inactivas'],['pendiente','pendientes','espera'],['recibido','recibida','recibidos','recibidas'],['comprado','comprada','compra','compras'],['metros','metro','m'],['pieza','piezas','pz','pza'],['milimetro','milímetro','milimetros','milímetros','mm'],['mm2','mm²'],['awg','calibre'],['factura','facturas','cfdi'],['recibo','comprobante','ticket'],['nomina','nómina','sueldo','sueldos'],['asistencia','asistencias','incidencia','incidencias'],['documento','documentos','contrato','contratos'],['capacitacion','capacitación','curso','cursos'],['presupuesto','presupuestos','costo','costos','gasto','gastos'],['paquete','paquetes','combo','combos','kit','kits','maleta','maletas','bolsa','bolsas','predeterminado','predeterminados']];
const FR={'¼':'1/4','½':'1/2','¾':'3/4','⅛':'1/8','⅜':'3/8','⅝':'5/8','⅞':'7/8','⅓':'1/3','⅔':'2/3'};
const WORDNUM=[[/\bun cuarto\b/g,'1/4'],[/\bcuarto de pulgada\b/g,'1/4'],[/\bmedia pulgada\b/g,'1/2'],[/\bmedio pulgada\b/g,'1/2'],[/\btres cuartos\b/g,'3/4'],[/\bun medio\b/g,'1/2'],[/\buna pulgada\b/g,'1'],[/\buna y media\b/g,'1 1/2'],[/\buno y media\b/g,'1 1/2']];
const stripCache=new Map(),normCache=new Map(),looseCache=new Map(),compactCache=new Map(),tokenCache=new Map(),queryCache=new Map(),scoreCache=new WeakMap();
const cached=(map,key,fn)=>{key=String(key??'');if(map.has(key))return map.get(key);const val=fn(key);if(map.size>3000)map.clear();map.set(key,val);return val};
const strip=v=>cached(stripCache,v,s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,''));
const word=v=>strip(v).toLowerCase().trim();
const ALIAS=new Map();GROUPS.forEach(g=>{const n=g.map(word);n.forEach(x=>ALIAS.set(x,n))});
function normalize(v){return cached(normCache,v,s=>{Object.entries(FR).forEach(([a,b])=>s=s.split(a).join(b));s=strip(s).toLowerCase().replace(/[“”„‟″]/g,'"').replace(/[‘’´`]/g,"'").replace(/[×✕✖·]/g,'x').replace(/mm²/g,'mm2');WORDNUM.forEach(([a,b])=>s=s.replace(a,b));return s.replace(/\b(pulgadas?|pulg\.?|inches?|inch)\b/g,' ').replace(/\b(numero|numero|num\.?|nro\.?|no\.?|calibre)\s*#?\s*(\d+)/g,'#$2').replace(/\s*[xX]\s*/g,'x').replace(/\s*\/\s*/g,'/').replace(/#\s+/g,'#').replace(/(\d)\s*"/g,'$1').replace(/[^a-z0-9@._+#\/\-\sx]/g,' ').replace(/\s+/g,' ').trim()})}
function loose(v){return cached(looseCache,v,s=>normalize(s).replace(/[@._+#\/\\:;|()\[\]{}<>,!?¿¡%&=~^$*'"`\-]+/g,' ').replace(/\s+/g,' ').trim())}
function compact(v){return cached(compactCache,v,s=>normalize(s).replace(/[^a-z0-9]/g,''))}
function semanticTokens(v){return normalize(v).split(/\s+/).map(x=>x.replace(/^[-]+|[-]+$/g,'')).filter(Boolean)}
function tokenParts(token){const out=new Set([token]);token.split(/[@._+#\/\\:;|()\[\]{}<>,!?¿¡%&=~^$*'"`\-]+/).filter(Boolean).forEach(x=>out.add(x));const c=compact(token);if(c&&c!==token)out.add(c);return[...out]}
function rawTokens(v){return cached(tokenCache,v,s=>{const out=new Set();semanticTokens(s).forEach(t=>tokenParts(t).forEach(x=>out.add(x)));loose(s).split(/\s+/).filter(Boolean).forEach(t=>out.add(t));return[...out]})}
function singulars(t){const out=new Set([t]);if(t.length>4&&t.endsWith('es'))out.add(t.slice(0,-2));if(t.length>3&&t.endsWith('s'))out.add(t.slice(0,-1));if(t.length>5&&t.endsWith('as'))out.add(t.slice(0,-2)+'a');if(t.length>5&&t.endsWith('os'))out.add(t.slice(0,-2)+'o');return[...out]}
function variants(t){const n=word(t),out=new Set(singulars(n));const g=ALIAS.get(n);if(g)g.forEach(x=>out.add(x));[...out].forEach(x=>{const a=ALIAS.get(x);if(a)a.forEach(y=>out.add(y))});return[...out]}
function meaningful(v){return rawTokens(v).filter(t=>/\d|@|#|\//.test(t)||t.length>=2&&!STOP.has(t))}
function lev(a,b,limit=2){if(a===b)return 0;if(Math.abs(a.length-b.length)>limit)return limit+1;let p=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const c=[i];let min=i;for(let j=1;j<=b.length;j++){const val=Math.min(c[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));c[j]=val;min=Math.min(min,val)}if(min>limit)return limit+1;p=c}return p[b.length]}
function canon(v){if(/^\d+\/\d+$/.test(v)){const[a,b]=v.split('/').map(Number);if(b)return String(Math.round(a/b*10000)/10000)}const n=Number(String(v).replace(/^#/,''));return Number.isFinite(n)?`${String(v).startsWith('#')?'#':''}${n}`:String(v)}
function dimensions(v){const s=normalize(v),out=new Set();let m;const re=/(#?\d+(?:\.\d+)?|\d+\/\d+)x(\d+(?:\.\d+)?|\d+\/\d+)/g;while((m=re.exec(s)))out.add(`${canon(m[1])}x${canon(m[2])}`);return out}
function parseQuery(v){return cached(queryCache,v,source=>{const quoted=[...source.matchAll(/"([^"]+)"/g)].map(m=>loose(m[1])).filter(Boolean),negative=[...source.matchAll(/(?:^|\s)-([^\s]+)/g)].map(m=>loose(m[1])).filter(Boolean),cleaned=source.replace(/"[^"]+"/g,' ').replace(/(?:^|\s)-[^\s]+/g,' ');return{normalized:normalize(source),loose:loose(source),compact:compact(source),quoted,negative,tokens:meaningful(cleaned),dimensions:[...dimensions(source)]}})}
function sourceText(values){return Array.isArray(values)?values.flat(Infinity).filter(v=>v!=null).join(' '):String(values??'')}
function tokenScore(targetTokens,targetNorm,targetLoose,t){let best=-1;for(const v of variants(t)){if(!v)continue;const vc=compact(v);if(targetTokens.has(v))best=Math.max(best,60);if(v.length>=2&&(targetNorm.includes(v)||targetLoose.includes(v)))best=Math.max(best,42);if(vc.length>=2&&compact(targetNorm).includes(vc))best=Math.max(best,39);if(v.length>=3){for(const x of targetTokens){if(x.startsWith(v)||v.startsWith(x))best=Math.max(best,32);if(v.length>=5&&x.length>=5){const lim=Math.max(v.length,x.length)>=9?2:1;if(lev(v,x,lim)<=lim)best=Math.max(best,24)}}}}return best}
function score(values,query){const q=parseQuery(query);if(!q.normalized)return 1;const source=sourceText(values);let memo=null;if(values&&typeof values==='object'){memo=scoreCache.get(values);if(!memo){memo=new Map();scoreCache.set(values,memo)}const k=q.normalized;if(memo.has(k))return memo.get(k)}const tNorm=normalize(source),tLoose=loose(source),tCompact=compact(source);let total=-1;if(tNorm){for(const n of q.negative)if(n&&tLoose.includes(n)){if(memo)memo.set(q.normalized,-1);return-1}for(const phrase of q.quoted)if(!tLoose.includes(phrase)){if(memo)memo.set(q.normalized,-1);return-1}total=0;if(tNorm===q.normalized||tLoose===q.loose)total+=290;else if(tNorm.startsWith(q.normalized)||tLoose.startsWith(q.loose))total+=210;else if(tNorm.includes(q.normalized)||tLoose.includes(q.loose))total+=180;if(q.compact.length>=2&&tCompact.includes(q.compact))total+=150;const td=dimensions(source);if(q.dimensions.length){let hit=0;q.dimensions.forEach(d=>{if(td.has(d))hit++});if(hit<q.dimensions.length){if(memo)memo.set(q.normalized,-1);return-1}total+=100+hit*20}const tt=new Set(rawTokens(source));let hits=0;for(const token of q.tokens){const part=tokenScore(tt,tNorm,tLoose,token);if(part>=0){hits++;total+=part}else if(/\d/.test(token)||token.includes('@')||token.includes('#')){if(memo)memo.set(q.normalized,-1);return-1}}if(q.tokens.length){const required=q.tokens.length<=2?q.tokens.length:Math.ceil(q.tokens.length*.6);if(hits<required)total=-1;else if(hits===q.tokens.length)total+=50}if(!q.tokens.length&&!q.dimensions.length&&!q.quoted.length&&total<=0)total=-1}if(memo)memo.set(q.normalized,total);return total}
function matches(values,q){return score(values,q)>=0}
function rank(items,q,getter){const src=Array.isArray(items)?items:[],get=typeof getter==='function'?getter:x=>x;if(!String(q??'').trim())return src.slice();return src.map((item,index)=>({item,index,s:score(get(item),q)})).filter(x=>x.s>=0).sort((a,b)=>b.s-a.s||a.index-b.index).map(x=>x.item)}
function rankTop(items,q,getter,limit=30){return rank(items,q,getter).slice(0,Math.max(0,limit||0))}
function searchRows(items,q,fields,limit=100){return rankTop(items,q,item=>typeof fields==='function'?fields(item):fields.map(f=>item?.[f]),limit)}
function explain(q){const p=parseQuery(q);return{normalized:p.normalized,loose:p.loose,compact:p.compact,tokens:p.tokens,dimensions:p.dimensions,quoted:p.quoted,negative:p.negative}}
function highlight(value,q){const source=String(value??''),tokens=explain(q).tokens.filter(t=>t.length>1).slice(0,8);let out=source.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');tokens.sort((a,b)=>b.length-a.length).forEach(t=>{const safe=t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');try{out=out.replace(new RegExp(`(${safe})`,'ig'),'<mark>$1</mark>')}catch(_){}});return out}
function debounce(fn,wait=90){let timer=0;return function(...args){clearTimeout(timer);timer=setTimeout(()=>fn.apply(this,args),wait)}}
function wireInput(input,callback,wait=90){const node=typeof input==='string'?document.querySelector(input):input;if(!node||typeof callback!=='function')return false;const run=debounce(()=>callback(node.value,node),wait);node.addEventListener('input',run);node.addEventListener('search',run);return true}
window.SkilledSearch=Object.freeze({normalize,loose,compact,tokens:rawTokens,score,matches,rank,rankTop,searchRows,explain,dimensionSignatures:dimensions,parseQuery,highlight,debounce,wireInput});
})();
