(function(){
'use strict';
const STOP=new Set('a al algo ante bajo cada como con contra cual cuales cuanto cuantos cuanta cuantas de del desde donde el ella en entre es ese esa esos esas esta este esto hay la las lo los me mi para por que se sin sobre su sus un una unos unas y o buscar busca buscame buscarme muestra muestrame mostrar ver quiero necesito dame checa checame revisa revisame encuentra encontrar dime saber saberme tengo tenemos existe existen registrado registrada registrados registradas'.split(' '));
const GROUPS=[
['pija','pijas','tornillo','tornillos','autotaladrante','autotaladrantes','autorroscante','autorroscantes'],['tubo','tubos','tuberia','tuberias','conduit'],['cincho','cinchos','cintillo','cintillos','tyrap','tyraps','tie','wrap'],['desarmador','desarmadores','destornillador','destornilladores'],['esmeril','esmeriles','amoladora','amoladoras'],['montacargas','forklift'],['camioneta','pickup','troca'],['automovil','auto','carro','coche'],['cable','cables','conductor','conductores'],['contacto','tomacorriente','receptaculo'],['apagador','interruptor'],['foco','lampara','luminaria'],['cople','copla','union'],['abrazadera','abrazaderas','grapa','grapas'],['rondana','rondanas','arandela','arandelas'],['tuerca','tuercas','nut'],['broca','brocas','mecha','mechas'],['casco','cascos','yelmo'],['lentes','gafas','anteojos'],['bota','botas','calzado'],['almacen','almacenes','bodega','bodegas'],['herramienta','herramientas','hta'],['orden','ordenes','oc'],['proyecto','proyectos','proy'],['proveedor','proveedores','prov'],['cotizacion','cotizaciones','cotiza','cotizar'],['requisicion','requisiciones','solicitud','solicitudes'],['correo','email','mail'],['telefono','telefonos','celular','celulares','whatsapp','wa'],['trabajador','trabajadores','empleado','empleados','colaborador','colaboradores','personal'],['vehiculo','vehiculos','flotilla'],['entrada','entradas','ingreso','ingresos'],['salida','salidas','entrega','entregas'],['disponible','disponibles','libre','libres'],['asignado','asignada','asignados','asignadas'],['mantenimiento','reparacion','taller'],['activo','activa','activos','activas'],['inactivo','inactiva','inactivos','inactivas'],['pendiente','pendientes','espera'],['recibido','recibida','recibidos','recibidas'],['comprado','comprada','compra','compras'],['metros','metro','m'],['pieza','piezas','pz','pza'],['milimetro','milimetros','mm'],['mm2','mm²'],['awg','calibre']
];
const strip=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const word=v=>strip(v).toLowerCase().trim();
const ALIAS=new Map();GROUPS.forEach(g=>{const n=g.map(word);n.forEach(x=>ALIAS.set(x,n))});
const FR={'¼':'1/4','½':'1/2','¾':'3/4','⅛':'1/8','⅜':'3/8','⅝':'5/8','⅞':'7/8','⅓':'1/3','⅔':'2/3'};
const WORDNUM=[[/\bun cuarto\b/g,'1/4'],[/\bcuarto de pulgada\b/g,'1/4'],[/\bmedia pulgada\b/g,'1/2'],[/\bmedio pulgada\b/g,'1/2'],[/\btres cuartos\b/g,'3/4'],[/\bun medio\b/g,'1/2'],[/\buna pulgada\b/g,'1'],[/\buna y media\b/g,'1 1/2']];
function normalize(v){let s=String(v??'');Object.entries(FR).forEach(([a,b])=>s=s.split(a).join(b));s=strip(s).toLowerCase().replace(/[“”„‟″]/g,'"').replace(/[‘’´`]/g,"'").replace(/[×✕✖·]/g,'x').replace(/mm²/g,'mm2');WORDNUM.forEach(([a,b])=>s=s.replace(a,b));return s.replace(/\b(pulgadas?|pulg\.?|inches?|inch)\b/g,' ').replace(/\b(numero|num\.?|nro\.?|no\.?|calibre)\s*#?\s*(\d+)/g,'#$2').replace(/\s*[xX]\s*/g,'x').replace(/\s*\/\s*/g,'/').replace(/#\s+/g,'#').replace(/(\d)\s*"/g,'$1').replace(/[^a-z0-9@._+#\/\-\sx]/g,' ').replace(/\s+/g,' ').trim()}
function compact(v){return normalize(v).replace(/[^a-z0-9@._+#\/x-]/g,'')}
function rawTokens(v){return normalize(v).split(/\s+/).map(x=>x.replace(/^[-]+|[-]+$/g,'')).filter(Boolean)}
function singulars(t){const out=new Set([t]);if(t.length>4&&t.endsWith('es'))out.add(t.slice(0,-2));if(t.length>3&&t.endsWith('s'))out.add(t.slice(0,-1));if(t.length>5&&t.endsWith('as'))out.add(t.slice(0,-2)+'a');if(t.length>5&&t.endsWith('os'))out.add(t.slice(0,-2)+'o');return [...out]}
function variants(t){const n=word(t),out=new Set(singulars(n));const g=ALIAS.get(n);if(g)g.forEach(x=>out.add(x));[...out].forEach(x=>{const a=ALIAS.get(x);if(a)a.forEach(y=>out.add(y))});return [...out]}
function meaningful(v){return rawTokens(v).filter(t=>/\d|@|#|\//.test(t)||t.length>=2&&!STOP.has(t))}
function lev(a,b,limit=2){if(a===b)return 0;if(Math.abs(a.length-b.length)>limit)return limit+1;let p=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const c=[i];let min=i;for(let j=1;j<=b.length;j++){const val=Math.min(c[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));c[j]=val;min=Math.min(min,val)}if(min>limit)return limit+1;p=c}return p[b.length]}
function dimensions(v){const s=normalize(v),out=new Set();let m;const add=(a,b)=>out.add(`${canon(a)}x${canon(b)}`);const re=/(#?\d+(?:\.\d+)?|\d+\/\d+)x(\d+(?:\.\d+)?|\d+\/\d+)/g;while((m=re.exec(s)))add(m[1],m[2]);return out}
function canon(v){if(/^\d+\/\d+$/.test(v)){const[a,b]=v.split('/').map(Number);if(b)return String(Math.round(a/b*10000)/10000)}const n=Number(String(v).replace(/^#/,''));return Number.isFinite(n)?`${String(v).startsWith('#')?'#':''}${n}`:String(v)}
function parseQuery(v){const source=String(v??''),quoted=[...source.matchAll(/"([^"]+)"/g)].map(m=>normalize(m[1])).filter(Boolean),negative=[...source.matchAll(/(?:^|\s)-([^\s]+)/g)].map(m=>normalize(m[1])).filter(Boolean),cleaned=source.replace(/"[^"]+"/g,' ').replace(/(?:^|\s)-[^\s]+/g,' ');return{normalized:normalize(source),quoted,negative,tokens:meaningful(cleaned),dimensions:[...dimensions(source)]}}
function tokenScore(targetTokens,targetNorm,t){let best=-1;for(const v of variants(t)){if(!v)continue;if(targetTokens.has(v))best=Math.max(best,48);if(v.length>=2&&targetNorm.includes(v))best=Math.max(best,34);if(v.length>=3){for(const x of targetTokens){if(x.startsWith(v)||v.startsWith(x))best=Math.max(best,29);if(v.length>=5&&x.length>=5){const lim=Math.max(v.length,x.length)>=9?2:1;if(lev(v,x,lim)<=lim)best=Math.max(best,22)}}}}return best}
function score(values,query){const source=Array.isArray(values)?values.flat(Infinity).filter(v=>v!=null).join(' '):String(values??''),q=parseQuery(query);if(!q.normalized)return 1;const tNorm=normalize(source);if(!tNorm)return-1;for(const n of q.negative)if(n&&tNorm.includes(n))return-1;for(const phrase of q.quoted)if(!tNorm.includes(phrase))return-1;let total=0;const qCompact=compact(query),tCompact=compact(source);if(tNorm===q.normalized)total+=260;else if(tNorm.startsWith(q.normalized))total+=190;else if(tNorm.includes(q.normalized))total+=165;if(qCompact.length>=3&&tCompact.includes(qCompact))total+=130;const td=dimensions(source);if(q.dimensions.length){let hit=0;q.dimensions.forEach(d=>{if(td.has(d))hit++});if(hit<q.dimensions.length)return-1;total+=90+hit*18}const tt=new Set(rawTokens(source));let hits=0;for(const token of q.tokens){const part=tokenScore(tt,tNorm,token);if(part>=0){hits++;total+=part}else if(/\d/.test(token)||token.includes('@')||token.includes('#'))return-1}if(q.tokens.length){const required=q.tokens.length<=2?q.tokens.length:Math.ceil(q.tokens.length*.65);if(hits<required)return-1;if(hits===q.tokens.length)total+=42}if(!q.tokens.length&&!q.dimensions.length&&!q.quoted.length&&total<=0)return-1;return total}
function matches(values,q){return score(values,q)>=0}
function rank(items,q,getter){const src=Array.isArray(items)?items:[],get=typeof getter==='function'?getter:x=>x;return src.map((item,index)=>({item,index,s:score(get(item),q)})).filter(x=>x.s>=0).sort((a,b)=>b.s-a.s||a.index-b.index).map(x=>x.item)}
function explain(q){const p=parseQuery(q);return{normalized:p.normalized,compact:compact(q),tokens:p.tokens,dimensions:p.dimensions,quoted:p.quoted,negative:p.negative}}
function highlight(value,q){const source=String(value??''),tokens=explain(q).tokens.filter(t=>t.length>1).slice(0,6);if(!tokens.length)return source.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');let out=source.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');tokens.sort((a,b)=>b.length-a.length).forEach(t=>{const safe=t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');out=out.replace(new RegExp(`(${safe})`,'ig'),'<mark>$1</mark>')});return out}
window.SkilledSearch=Object.freeze({normalize,compact,score,matches,rank,explain,dimensionSignatures:dimensions,parseQuery,highlight});
})();
