window.SKILLED_CONFIG=Object.assign({
  supabaseUrl:'https://pibvfosvufbwbnwfwbmw.supabase.co',
  supabasePublishableKey:'sb_publishable_wBuo5rXuwnytiH9HLqLzBw__SdFx7NP',
  skillLocalAiUrl:'',
  skillLocalTtsUrl:'',
  skillMeetingBridgeUrl:'',
  skillMeetingBridgeToken:'',
  skillMeetingEmailMode:'auto',
  deploymentMode:'cloud'
},window.SKILLED_CONFIG||{});
