window.SKILLED_CONFIG=Object.assign({
  supabaseUrl:'https://cuxnzqbszzrfnrinxbdp.supabase.co',
  supabasePublishableKey:'sb_publishable_eAnp6imD2nOqrtL_A-xrSA_p-bmoLQF',
  skillLocalAiUrl:'',
  skillLocalTtsUrl:'',
  skillMeetingBridgeUrl:'',
  skillMeetingBridgeToken:'',
  deploymentMode:'cloud'
},window.SKILLED_CONFIG||{});
