begin;

insert into public.perfiles_usuario(id,nombre,rol,activo)
select u.id,
       coalesce(nullif(u.raw_user_meta_data->>'nombre',''),split_part(u.email,'@',1)),
       'recepcion',
       true
  from auth.users u
 where lower(coalesce(u.email,''))='recepcion@skilled.mx'
on conflict(id) do update
   set rol='recepcion',
       activo=true,
       updated_at=now();

create table if not exists public.re_suministros (
    id bigint generated by default as identity primary key,
    codigo text not null unique,
    descripcion text not null,
    modismos text[] not null default '{}'::text[],
    categoria text not null default 'General',
    marca text,
    codigo_marca text,
    proveedor text,
    contacto_proveedor text,
    unidad text not null default 'PIEZA',
    stock numeric(16,4) not null default 0 check (stock >= 0),
    stock_minimo numeric(16,4) not null default 0 check (stock_minimo >= 0),
    stock_medio numeric(16,4) not null default 0 check (stock_medio >= 0),
    stock_maximo numeric(16,4) not null default 0 check (stock_maximo >= 0),
    precio numeric(16,4) not null default 0 check (precio >= 0),
    moneda_costo text not null default 'MXN' check (moneda_costo in ('MXN','USD','EUR')),
    imagen_url text,
    activo boolean not null default true,
    creado_por uuid references auth.users(id) on delete set null default auth.uid(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists re_suministros_activo_idx on public.re_suministros(activo);
create index if not exists re_suministros_categoria_idx on public.re_suministros(categoria);
create index if not exists re_suministros_descripcion_idx on public.re_suministros(lower(descripcion));
drop trigger if exists trg_re_suministros_fecha on public.re_suministros;
create trigger trg_re_suministros_fecha before update on public.re_suministros for each row execute function public.co_actualizar_fecha();

alter table public.re_suministros enable row level security;
drop policy if exists "Recepción consulta re_suministros" on public.re_suministros;
create policy "Recepción consulta re_suministros" on public.re_suministros
for select to authenticated
using (public.crm_usuario_tiene_rol(array['administrador','recepcion']));
drop policy if exists "Recepción administra re_suministros" on public.re_suministros;
create policy "Recepción administra re_suministros" on public.re_suministros
for all to authenticated
using (public.crm_usuario_tiene_rol(array['administrador','recepcion']))
with check (public.crm_usuario_tiene_rol(array['administrador','recepcion']));
grant select,insert,update,delete on public.re_suministros to authenticated;
grant usage,select on sequence public.re_suministros_id_seq to authenticated;

alter table public.co_tienda_solicitudes drop constraint if exists co_tienda_solicitudes_folio_key;
create index if not exists co_tienda_folio_idx on public.co_tienda_solicitudes(folio);

alter table public.co_tienda_solicitudes enable row level security;
drop policy if exists "Compras consulta co_tienda_solicitudes" on public.co_tienda_solicitudes;
drop policy if exists "Compras administra co_tienda_solicitudes" on public.co_tienda_solicitudes;
drop policy if exists "Recepción consulta co_tienda_solicitudes" on public.co_tienda_solicitudes;
create policy "Recepción consulta co_tienda_solicitudes" on public.co_tienda_solicitudes
for select to authenticated
using (public.crm_usuario_tiene_rol(array['administrador','recepcion']));
drop policy if exists "Recepción administra co_tienda_solicitudes" on public.co_tienda_solicitudes;
create policy "Recepción administra co_tienda_solicitudes" on public.co_tienda_solicitudes
for all to authenticated
using (public.crm_usuario_tiene_rol(array['administrador','recepcion']))
with check (public.crm_usuario_tiene_rol(array['administrador','recepcion']));
grant select,insert,update,delete on public.co_tienda_solicitudes to authenticated;

alter table public.solicitudes_compra add column if not exists cotizacion_id uuid references public.co_cotizaciones(id) on update cascade on delete set null;
alter table public.solicitudes_compra add column if not exists cotizacion_item_id bigint references public.co_cotizacion_items(id) on update cascade on delete set null;
alter table public.solicitudes_compra add column if not exists proveedor_id bigint references public.co_proveedores(id) on update cascade on delete set null;
alter table public.solicitudes_compra add column if not exists precio_cotizado numeric(16,4) not null default 0;
alter table public.solicitudes_compra add column if not exists moneda text not null default 'MXN';
alter table public.solicitudes_compra add column if not exists plazo_entrega_dias integer not null default 0;
alter table public.solicitudes_compra add column if not exists origen_solicitud text not null default 'bajo_minimo';
alter table public.solicitudes_compra add column if not exists justificacion_excepcion text;
alter table public.co_cotizaciones add column if not exists oc_generada_at timestamptz;
create index if not exists solicitudes_compra_cotizacion_idx on public.solicitudes_compra(cotizacion_id,cotizacion_item_id);

create table if not exists public.co_orden_firmas (
    id bigint generated by default as identity primary key,
    orden_compra text not null,
    tipo text not null check (tipo in ('solicito','elaboro','reviso','aprobo')),
    nombre text not null,
    firma_data_url text not null,
    user_id uuid not null default auth.uid(),
    firmado_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique(orden_compra,tipo)
);
create index if not exists co_orden_firmas_orden_idx on public.co_orden_firmas(orden_compra);
alter table public.co_orden_firmas enable row level security;
drop policy if exists co_orden_firmas_select on public.co_orden_firmas;
create policy co_orden_firmas_select on public.co_orden_firmas for select to authenticated using (true);
drop policy if exists co_orden_firmas_insert on public.co_orden_firmas;
create policy co_orden_firmas_insert on public.co_orden_firmas for insert to authenticated with check (user_id=auth.uid());
drop policy if exists co_orden_firmas_update on public.co_orden_firmas;
create policy co_orden_firmas_update on public.co_orden_firmas for update to authenticated using (user_id=auth.uid() or public.crm_usuario_tiene_rol(array['administrador','compras'])) with check (user_id=auth.uid() or public.crm_usuario_tiene_rol(array['administrador','compras']));
drop policy if exists co_orden_firmas_delete on public.co_orden_firmas;
create policy co_orden_firmas_delete on public.co_orden_firmas for delete to authenticated using (user_id=auth.uid() or public.crm_usuario_tiene_rol(array['administrador','compras']));
grant select,insert,update,delete on public.co_orden_firmas to authenticated;
grant usage,select on sequence public.co_orden_firmas_id_seq to authenticated;

create or replace function public.co_crear_orden_directa_cotizacion_v103(
    p_cotizacion_id uuid,
    p_orden text,
    p_proveedor_id bigint,
    p_referencia text,
    p_solicitado_por text,
    p_notas text,
    p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
    v_cot public.co_cotizaciones%rowtype;
    v_order text:=upper(btrim(coalesce(p_orden,'')));
    v_provider_name text;
    v_provider_contact text;
    v_priority text;
    v_count integer:=0;
    v_remaining integer:=0;
begin
    if not public.crm_usuario_tiene_rol(array['administrador','compras']) then
        raise exception using errcode='42501',message='Solo Compras o Administrador puede generar una orden directa desde cotización.';
    end if;
    if p_items is null or jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then
        raise exception 'La orden no contiene partidas.';
    end if;
    if coalesce(p_proveedor_id,0)<=0 then
        raise exception 'Selecciona el proveedor de la orden directa.';
    end if;

    select * into v_cot from public.co_cotizaciones where id=p_cotizacion_id for update;
    if not found then raise exception 'La solicitud de cotización ya no existe.'; end if;

    select coalesce(nullif(nombre_comercial,''),razon_social),contacto
      into v_provider_name,v_provider_contact
      from public.co_proveedores
     where id=p_proveedor_id and estado<>'inactivo';
    if v_provider_name is null then raise exception 'El proveedor seleccionado ya no está disponible.'; end if;

    if exists(
        select 1
          from public.solicitudes_compra sc
          join jsonb_to_recordset(p_items) as x(cotizacion_item_id bigint,precio_unitario numeric,moneda text,plazo_entrega_dias integer)
            on x.cotizacion_item_id=sc.cotizacion_item_id
         where sc.cotizacion_id=p_cotizacion_id
           and lower(coalesce(sc.estado,'')) not in ('cancelada','recibida')
    ) then
        raise exception 'Una o más partidas seleccionadas ya tienen una orden de compra activa.';
    end if;

    if exists(
        select 1
          from jsonb_to_recordset(p_items) as x(cotizacion_item_id bigint,precio_unitario numeric,moneda text,plazo_entrega_dias integer)
          left join public.co_cotizacion_items ci on ci.id=x.cotizacion_item_id and ci.cotizacion_id=p_cotizacion_id
         where ci.id is null or ci.estado='cerrado'
    ) then
        raise exception 'Una o más partidas ya no están disponibles para generar orden.';
    end if;

    if v_order='' then
        v_order:='OC-DIR-'||to_char(clock_timestamp(),'YYYYMMDD-HH24MISS')||'-'||upper(substr(md5(random()::text),1,3));
    end if;
    v_priority:=case when lower(coalesce(v_cot.prioridad,'normal')) in('critica','urgente','alta') then 'urgente' else 'normal' end;

    insert into public.solicitudes_compra(
        folio,material_codigo,descripcion,categoria,unidad,almacen_id,almacen_nombre,
        existencia_actual,stock_minimo,stock_medio,stock_maximo,cantidad_solicitada,cantidad_recibida,
        prioridad,estado,proveedor,contacto_proveedor,orden_compra,grupo_orden,motivo,solicitado_por,
        fecha_requerida,fecha_orden_compra,referencia,estado_compras,cotizacion_id,cotizacion_item_id,
        proveedor_id,precio_cotizado,moneda,plazo_entrega_dias,origen_solicitud,justificacion_excepcion,created_at,updated_at
    )
    select
        'SC-DIR-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS')||'-'||lpad(row_number() over()::text,3,'0'),
        ci.material_codigo,ci.descripcion,m.categoria,coalesce(nullif(ci.unidad,''),m.unidad),ci.almacen_id,ci.almacen_nombre,
        ci.existencia_actual,ci.stock_minimo,ci.stock_medio,ci.stock_maximo,ci.cantidad,0,
        v_priority,'pendiente',v_provider_name,v_provider_contact,v_order,v_order,
        'Orden directa desde solicitud de cotización '||v_cot.folio||case when btrim(coalesce(p_notas,''))<>'' then ': '||btrim(p_notas) else '' end,
        coalesce(nullif(btrim(coalesce(p_solicitado_por,'')),''),v_cot.solicitado_por),
        v_cot.fecha_requerida,current_date,coalesce(nullif(btrim(coalesce(p_referencia,'')),''),v_cot.referencia),'en_revision',
        p_cotizacion_id,ci.id,p_proveedor_id,greatest(coalesce(x.precio_unitario,0),0),
        case upper(coalesce(x.moneda,'MXN')) when 'USD' then 'USD' when 'EUR' then 'EUR' else 'MXN' end,
        greatest(coalesce(x.plazo_entrega_dias,0),0),'cotizacion_directa','Orden directa desde cotización',now(),now()
      from jsonb_to_recordset(p_items) as x(cotizacion_item_id bigint,precio_unitario numeric,moneda text,plazo_entrega_dias integer)
      join public.co_cotizacion_items ci on ci.id=x.cotizacion_item_id and ci.cotizacion_id=p_cotizacion_id and ci.estado<>'cerrado'
      left join public.materiales m on lower(m.codigo)=lower(ci.material_codigo);
    get diagnostics v_count=row_count;
    if v_count=0 then raise exception 'No se pudieron crear partidas para la orden directa.'; end if;

    update public.co_cotizacion_ofertas o
       set estado=case when o.proveedor_id=p_proveedor_id then 'seleccionada' else 'descartada' end,
           updated_at=now()
     where o.cotizacion_item_id in (
        select x.cotizacion_item_id
          from jsonb_to_recordset(p_items) as x(cotizacion_item_id bigint,precio_unitario numeric,moneda text,plazo_entrega_dias integer)
     );

    update public.co_cotizacion_items ci
       set estado='cerrado',
           proveedor_seleccionado_id=p_proveedor_id,
           oferta_seleccionada_id=(select o.id from public.co_cotizacion_ofertas o where o.cotizacion_item_id=ci.id and o.proveedor_id=p_proveedor_id order by o.id limit 1),
           updated_at=now()
     where ci.cotizacion_id=p_cotizacion_id
       and ci.id in (
          select x.cotizacion_item_id
            from jsonb_to_recordset(p_items) as x(cotizacion_item_id bigint,precio_unitario numeric,moneda text,plazo_entrega_dias integer)
       );

    select count(*) into v_remaining from public.co_cotizacion_items where cotizacion_id=p_cotizacion_id and estado<>'cerrado';

    if v_remaining=0 then
        update public.co_cotizaciones
           set estado='aprobada',
               aprobada_por=auth.uid(),
               aprobada_at=coalesce(aprobada_at,now()),
               revisada_por=coalesce(revisada_por,auth.uid()),
               revisada_at=coalesce(revisada_at,now()),
               oc_generada_at=coalesce(oc_generada_at,now()),
               updated_at=now()
         where id=p_cotizacion_id;
    else
        update public.co_cotizaciones
           set estado='comparada',
               revisada_por=coalesce(revisada_por,auth.uid()),
               revisada_at=coalesce(revisada_at,now()),
               oc_generada_at=coalesce(oc_generada_at,now()),
               updated_at=now()
         where id=p_cotizacion_id;
    end if;

    return jsonb_build_object('ok',true,'orden',v_order,'materiales',v_count,'pendientes',v_remaining,'cotizacion_id',p_cotizacion_id,'origen','cotizacion_directa_v103');
end;
$$;
revoke all on function public.co_crear_orden_directa_cotizacion_v103(uuid,text,bigint,text,text,text,jsonb) from public,anon;
grant execute on function public.co_crear_orden_directa_cotizacion_v103(uuid,text,bigint,text,text,text,jsonb) to authenticated;

create or replace function public.crm_sky_perfil_consultar_v103(p_fuente text,p_filtro text default null)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
    v_role text;
    v_fuente text:=lower(btrim(coalesce(p_fuente,'')));
    v_filtro text:=nullif(btrim(coalesce(p_filtro,'')),'');
    v_result jsonb:='[]'::jsonb;
begin
    if auth.uid() is null then raise exception using errcode='42501',message='La sesión no está activa.'; end if;
    select lower(btrim(p.rol)) into v_role from public.perfiles_usuario p where p.id=auth.uid() and p.activo=true;
    if v_role is null then raise exception using errcode='42501',message='Tu perfil no está activo para Skill.'; end if;

    v_fuente:=case v_fuente
        when 'projectdetails' then 'proyectos'
        when 'purchases' then 'compras'
        when 'suppliers' then 'proveedores'
        when 'quotations' then 'cotizaciones'
        else v_fuente
    end;

    if v_role not in ('gerente_general','subgerente','sky_demo') then
        if v_role='administrador' then raise exception using errcode='42501',message='Skill Administración no tiene acceso transversal a datos operativos.'; end if;
        if v_role in ('jefe_almacen','almacen') and v_fuente not in ('materiales','categorias','almacenes','herramientas','vehiculos','proyectos','compras') then raise exception using errcode='42501',message='Skill Almacén no puede consultar esa fuente.'; end if;
        if v_role='compras' and v_fuente not in ('materiales','categorias','proyectos','proveedores','compras','cotizaciones') then raise exception using errcode='42501',message='Skill Compras no puede consultar esa fuente.'; end if;
        if v_role='proyectos' and v_fuente not in ('proyectos','materiales','categorias','compras') then raise exception using errcode='42501',message='Skill Proyectos no puede consultar esa fuente.'; end if;
        if v_role='planeacion' and v_fuente not in ('proyectos','materiales','categorias','compras') then raise exception using errcode='42501',message='Skill Planeación no puede consultar esa fuente.'; end if;
        if v_role='coordinacion' and v_fuente not in ('proyectos','vehiculos','compras') then raise exception using errcode='42501',message='Skill Coordinación no puede consultar esa fuente.'; end if;
        if v_role='logistica' and v_fuente not in ('proyectos','vehiculos','materiales','categorias') then raise exception using errcode='42501',message='Skill Logística no puede consultar esa fuente.'; end if;
        if v_role='recepcion' and v_fuente not in ('suministros','tienda') then raise exception using errcode='42501',message='Skill Recepción solo puede consultar Suministros, Tienda y la presencia limitada de Recepción.'; end if;
        if v_role='rh' and v_fuente not in ('personal','proyectos','vehiculos') then raise exception using errcode='42501',message='Skill RH no puede consultar esa fuente.'; end if;
        if v_role='finanzas' and v_fuente not in ('proyectos','compras','cotizaciones') then raise exception using errcode='42501',message='Skill Finanzas no puede consultar esa fuente.'; end if;
        if v_role='tsi' and v_fuente not in ('materiales','categorias','proyectos') then raise exception using errcode='42501',message='Skill TSI no puede consultar esa fuente.'; end if;
        if v_role='consulta' and v_fuente not in ('materiales','categorias') then raise exception using errcode='42501',message='Skill Consulta no puede consultar esa fuente.'; end if;
        if v_role not in ('administrador','jefe_almacen','almacen','compras','proyectos','planeacion','coordinacion','logistica','recepcion','rh','finanzas','tsi','consulta') then raise exception using errcode='42501',message='Skill no está habilitado para este perfil.'; end if;
    end if;

    if v_fuente='suministros' then
        select coalesce(jsonb_agg(jsonb_build_object(
            'id',s.id,'codigo',s.codigo,'descripcion',s.descripcion,'modismos',to_jsonb(s.modismos),'categoria',s.categoria,
            'marca',s.marca,'codigo_marca',s.codigo_marca,'proveedor',s.proveedor,'contacto_proveedor',s.contacto_proveedor,
            'unidad',s.unidad,'stock',s.stock,'stock_minimo',s.stock_minimo,'stock_medio',s.stock_medio,'stock_maximo',s.stock_maximo,
            'precio',s.precio,'moneda_costo',s.moneda_costo,'imagen_url',s.imagen_url,'activo',s.activo
        ) order by s.descripcion),'[]'::jsonb)
          into v_result
          from public.re_suministros s
         where s.activo=true
           and (v_filtro is null or lower(concat_ws(' ',s.codigo,s.descripcion,s.categoria,s.marca,s.codigo_marca,s.proveedor,s.contacto_proveedor,array_to_string(s.modismos,' '))) like '%'||lower(v_filtro)||'%');
        return coalesce(v_result,'[]'::jsonb);
    end if;

    if v_fuente='tienda' then
        select coalesce(jsonb_agg(jsonb_build_object(
            'id',t.id,'folio',t.folio,'negocio',t.negocio,'producto',t.producto,'marcaEspecifica',t.marca_especifica,
            'presentacion',t.presentacion,'cantidad',t.cantidad,'unidad',t.unidad,'costoEstimado',t.costo_estimado,'moneda',t.moneda,
            'fechaRequerida',t.fecha_requerida,'prioridad',t.prioridad,'estado',t.estado,'solicitadoPor',t.solicitado_por,
            'responsableCompra',t.responsable_compra,'motivoNoViable',t.motivo_no_viable,'notas',t.notas,'createdAt',t.created_at
        ) order by t.created_at desc),'[]'::jsonb)
          into v_result
          from public.co_tienda_solicitudes t
         where v_filtro is null or lower(concat_ws(' ',t.folio,t.negocio,t.producto,t.marca_especifica,t.presentacion,t.estado,t.solicitado_por,t.responsable_compra,t.notas)) like '%'||lower(v_filtro)||'%';
        return coalesce(v_result,'[]'::jsonb);
    end if;

    return public.crm_sky_perfil_consultar(v_fuente,v_filtro);
end;
$$;
revoke all on function public.crm_sky_perfil_consultar_v103(text,text) from public,anon;
grant execute on function public.crm_sky_perfil_consultar_v103(text,text) to authenticated;

insert into public.crm_migraciones(version,aplicada_at)
values('CRM-V103-RECEPCION-SUMINISTROS-TIENDA-SKILL-OC-2026-08-19',now())
on conflict(version) do update set aplicada_at=excluded.aplicada_at;

notify pgrst,'reload schema';
commit;

select 'OK' as estado,
       'CRM-V103-RECEPCION-SUMINISTROS-TIENDA-SKILL-OC-2026-08-19' as revision,
       case when to_regclass('public.re_suministros') is not null then 'OK' else 'FALTA' end as suministros_recepcion,
       case when to_regprocedure('public.co_crear_orden_directa_cotizacion_v103(uuid,text,bigint,text,text,text,jsonb)') is not null then 'OK' else 'FALTA' end as orden_cotizacion_v103,
       case when to_regprocedure('public.crm_sky_perfil_consultar_v103(text,text)') is not null then 'OK' else 'FALTA' end as skill_perfiles_v103;
