begin;

create table if not exists public.crm_migraciones(version text primary key,aplicada_at timestamptz not null default now());

create table if not exists public.rh_activos_oficina(
    id bigint generated by default as identity primary key,
    codigo text not null,
    nombre text not null,
    categoria text not null default 'Otro',
    tipo_control text not null default 'individual',
    marca text,
    modelo text,
    numero_serie text,
    unidad text not null default 'PIEZA',
    cantidad_total numeric(14,2) not null default 1,
    ubicacion text,
    estado text not null default 'activo',
    observaciones text,
    creado_por uuid references auth.users(id) on delete set null default auth.uid(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.rh_activos_oficina drop constraint if exists rh_activos_oficina_tipo_control_check;
alter table public.rh_activos_oficina add constraint rh_activos_oficina_tipo_control_check check(tipo_control in ('individual','cantidad'));
alter table public.rh_activos_oficina drop constraint if exists rh_activos_oficina_estado_check;
alter table public.rh_activos_oficina add constraint rh_activos_oficina_estado_check check(estado in ('activo','mantenimiento','baja'));
alter table public.rh_activos_oficina drop constraint if exists rh_activos_oficina_cantidad_check;
alter table public.rh_activos_oficina add constraint rh_activos_oficina_cantidad_check check(cantidad_total>0);
create unique index if not exists rh_activos_oficina_codigo_uq on public.rh_activos_oficina(lower(codigo));
create unique index if not exists rh_activos_oficina_serie_uq on public.rh_activos_oficina(lower(numero_serie)) where nullif(btrim(numero_serie),'') is not null;
create index if not exists rh_activos_oficina_categoria_idx on public.rh_activos_oficina(categoria,estado);

create table if not exists public.rh_activos_asignaciones(
    id bigint generated by default as identity primary key,
    activo_id bigint not null references public.rh_activos_oficina(id) on update cascade on delete restrict,
    personal_id bigint not null references public.rh_personal(id) on update cascade on delete restrict,
    cantidad numeric(14,2) not null default 1,
    fecha_asignacion date not null default current_date,
    fecha_devolucion date,
    estado text not null default 'asignado',
    condicion_entrega text,
    condicion_devolucion text,
    responsable_entrega text,
    responsable_recepcion text,
    notas text,
    creado_por uuid references auth.users(id) on delete set null default auth.uid(),
    cerrado_por uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.rh_activos_asignaciones drop constraint if exists rh_activos_asignaciones_estado_check;
alter table public.rh_activos_asignaciones add constraint rh_activos_asignaciones_estado_check check(estado in ('asignado','devuelto','danado','perdido'));
alter table public.rh_activos_asignaciones drop constraint if exists rh_activos_asignaciones_cantidad_check;
alter table public.rh_activos_asignaciones add constraint rh_activos_asignaciones_cantidad_check check(cantidad>0);
create index if not exists rh_activos_asignaciones_personal_idx on public.rh_activos_asignaciones(personal_id,estado);
create index if not exists rh_activos_asignaciones_activo_idx on public.rh_activos_asignaciones(activo_id,estado);
create index if not exists rh_activos_asignaciones_fecha_idx on public.rh_activos_asignaciones(fecha_asignacion desc);

create or replace function public.rh_activo_oficina_actualizar_trg()
returns trigger
language plpgsql
set search_path=public
as $$
declare v_ocupado numeric(14,2):=0;
begin
    new.codigo=upper(btrim(coalesce(new.codigo,'')));
    new.nombre=btrim(coalesce(new.nombre,''));
    new.categoria=coalesce(nullif(btrim(coalesce(new.categoria,'')),''),'Otro');
    new.unidad=upper(coalesce(nullif(btrim(coalesce(new.unidad,'')),''),'PIEZA'));
    if new.codigo='' or new.nombre='' then raise exception using errcode='22023',message='Código y nombre son obligatorios.'; end if;
    if new.tipo_control='individual' then new.cantidad_total=1;new.unidad='PIEZA';end if;
    if tg_op='UPDATE' then
        select coalesce(sum(a.cantidad),0) into v_ocupado from public.rh_activos_asignaciones a where a.activo_id=old.id and a.estado in ('asignado','danado','perdido');
        if new.cantidad_total<v_ocupado then raise exception using errcode='22023',message=format('La cantidad total no puede ser menor a %s, porque esa cantidad sigue asignada, dañada o perdida.',v_ocupado);end if;
    end if;
    new.updated_at=now();
    return new;
end;
$$;

drop trigger if exists trg_rh_activo_oficina_actualizar on public.rh_activos_oficina;
create trigger trg_rh_activo_oficina_actualizar before insert or update on public.rh_activos_oficina for each row execute function public.rh_activo_oficina_actualizar_trg();

drop trigger if exists trg_rh_activos_asignaciones_fecha on public.rh_activos_asignaciones;
create trigger trg_rh_activos_asignaciones_fecha before update on public.rh_activos_asignaciones for each row execute function public.rh_actualizar_fecha();

alter table public.rh_activos_oficina enable row level security;
alter table public.rh_activos_asignaciones enable row level security;

drop policy if exists "RH consulta activos oficina" on public.rh_activos_oficina;
create policy "RH consulta activos oficina" on public.rh_activos_oficina for select to authenticated using(exists(select 1 from public.perfiles_usuario p where p.id=auth.uid() and p.activo=true and p.rol in ('administrador','rh')));
drop policy if exists "RH administra activos oficina" on public.rh_activos_oficina;
create policy "RH administra activos oficina" on public.rh_activos_oficina for all to authenticated using(exists(select 1 from public.perfiles_usuario p where p.id=auth.uid() and p.activo=true and p.rol in ('administrador','rh'))) with check(exists(select 1 from public.perfiles_usuario p where p.id=auth.uid() and p.activo=true and p.rol in ('administrador','rh')));

drop policy if exists "RH consulta resguardos" on public.rh_activos_asignaciones;
create policy "RH consulta resguardos" on public.rh_activos_asignaciones for select to authenticated using(exists(select 1 from public.perfiles_usuario p where p.id=auth.uid() and p.activo=true and p.rol in ('administrador','rh')) or exists(select 1 from public.rh_personal rp where rp.id=personal_id and rp.usuario_id=auth.uid()));
drop policy if exists "RH administra resguardos" on public.rh_activos_asignaciones;
create policy "RH administra resguardos" on public.rh_activos_asignaciones for all to authenticated using(exists(select 1 from public.perfiles_usuario p where p.id=auth.uid() and p.activo=true and p.rol in ('administrador','rh'))) with check(exists(select 1 from public.perfiles_usuario p where p.id=auth.uid() and p.activo=true and p.rol in ('administrador','rh')));

grant select,insert,update,delete on public.rh_activos_oficina to authenticated;
grant select,insert,update,delete on public.rh_activos_asignaciones to authenticated;
grant usage,select on sequence public.rh_activos_oficina_id_seq to authenticated;
grant usage,select on sequence public.rh_activos_asignaciones_id_seq to authenticated;

create or replace function public.rh_asignar_activo_oficina(p_activo_id bigint,p_personal_id bigint,p_cantidad numeric default 1,p_fecha_asignacion date default current_date,p_condicion_entrega text default null,p_responsable_entrega text default null,p_notas text default null)
returns bigint
language plpgsql
security definer
set search_path=public,auth
as $$
declare v_activo public.rh_activos_oficina%rowtype;v_ocupado numeric(14,2):=0;v_cantidad numeric(14,2);v_id bigint;
begin
    if not exists(select 1 from public.perfiles_usuario p where p.id=auth.uid() and p.activo=true and p.rol in ('administrador','rh')) then raise exception using errcode='42501',message='Solo RH puede registrar resguardos de equipo.';end if;
    select * into v_activo from public.rh_activos_oficina where id=p_activo_id for update;
    if not found then raise exception using errcode='P0002',message='El activo no existe.';end if;
    if v_activo.estado<>'activo' then raise exception using errcode='22023',message='El activo no está disponible para asignación.';end if;
    if not exists(select 1 from public.rh_personal rp where rp.id=p_personal_id and rp.estado<>'baja') then raise exception using errcode='22023',message='El colaborador no existe o está dado de baja.';end if;
    select coalesce(sum(a.cantidad),0) into v_ocupado from public.rh_activos_asignaciones a where a.activo_id=p_activo_id and a.estado in ('asignado','danado','perdido');
    v_cantidad=case when v_activo.tipo_control='individual' then 1 else greatest(coalesce(p_cantidad,1),0) end;
    if v_cantidad<=0 then raise exception using errcode='22023',message='La cantidad debe ser mayor a cero.';end if;
    if v_ocupado+v_cantidad>v_activo.cantidad_total then raise exception using errcode='22023',message=format('Solo hay %s %s disponibles.',greatest(v_activo.cantidad_total-v_ocupado,0),v_activo.unidad);end if;
    insert into public.rh_activos_asignaciones(activo_id,personal_id,cantidad,fecha_asignacion,estado,condicion_entrega,responsable_entrega,notas,creado_por) values(p_activo_id,p_personal_id,v_cantidad,coalesce(p_fecha_asignacion,current_date),'asignado',nullif(btrim(coalesce(p_condicion_entrega,'')),''),nullif(btrim(coalesce(p_responsable_entrega,'')),''),nullif(btrim(coalesce(p_notas,'')),''),auth.uid()) returning id into v_id;
    return v_id;
end;
$$;
revoke all on function public.rh_asignar_activo_oficina(bigint,bigint,numeric,date,text,text,text) from public,anon;
grant execute on function public.rh_asignar_activo_oficina(bigint,bigint,numeric,date,text,text,text) to authenticated;

create or replace function public.rh_cerrar_asignacion_activo_oficina(p_asignacion_id bigint,p_resultado text default 'devuelto',p_fecha_devolucion date default current_date,p_condicion_devolucion text default null,p_responsable_recepcion text default null,p_notas text default null)
returns bigint
language plpgsql
security definer
set search_path=public,auth
as $$
declare v_estado text:=lower(btrim(coalesce(p_resultado,'devuelto')));v_id bigint;
begin
    if not exists(select 1 from public.perfiles_usuario p where p.id=auth.uid() and p.activo=true and p.rol in ('administrador','rh')) then raise exception using errcode='42501',message='Solo RH puede cerrar resguardos de equipo.';end if;
    if v_estado not in ('devuelto','danado','perdido') then raise exception using errcode='22023',message='Resultado de devolución no válido.';end if;
    update public.rh_activos_asignaciones set estado=v_estado,fecha_devolucion=coalesce(p_fecha_devolucion,current_date),condicion_devolucion=nullif(btrim(coalesce(p_condicion_devolucion,'')),''),responsable_recepcion=nullif(btrim(coalesce(p_responsable_recepcion,'')),''),notas=case when nullif(btrim(coalesce(p_notas,'')),'') is null then notas when nullif(btrim(coalesce(notas,'')),'') is null then btrim(p_notas) else notas||E'\n'||btrim(p_notas) end,cerrado_por=auth.uid(),updated_at=now() where id=p_asignacion_id and estado='asignado' returning id into v_id;
    if v_id is null then raise exception using errcode='P0002',message='El resguardo no existe o ya fue cerrado.';end if;
    return v_id;
end;
$$;
revoke all on function public.rh_cerrar_asignacion_activo_oficina(bigint,text,date,text,text,text) from public,anon;
grant execute on function public.rh_cerrar_asignacion_activo_oficina(bigint,text,date,text,text,text) to authenticated;

create or replace function public.rh_eliminar_activo_oficina(p_activo_id bigint)
returns boolean
language plpgsql
security definer
set search_path=public,auth
as $$
begin
    if not exists(select 1 from public.perfiles_usuario p where p.id=auth.uid() and p.activo=true and p.rol in ('administrador','rh')) then raise exception using errcode='42501',message='Solo RH puede eliminar activos.';end if;
    if exists(select 1 from public.rh_activos_asignaciones where activo_id=p_activo_id) then raise exception using errcode='23503',message='El activo tiene historial de resguardos. Cámbialo a Baja para conservar la trazabilidad.';end if;
    delete from public.rh_activos_oficina where id=p_activo_id;
    return found;
end;
$$;
revoke all on function public.rh_eliminar_activo_oficina(bigint) from public,anon;
grant execute on function public.rh_eliminar_activo_oficina(bigint) to authenticated;

create or replace function public.crm_sky_direccion_activos_oficina()
returns jsonb
language plpgsql
stable
security definer
set search_path=public,auth
as $$
declare v_activos jsonb;v_asignaciones jsonb;
begin
    if not exists(select 1 from public.perfiles_usuario p where p.id=auth.uid() and p.activo=true and p.rol in ('administrador','gerente_general','subgerente')) then raise exception using errcode='42501',message='Esta consulta de Sky está disponible solo para Dirección.';end if;
    select coalesce(jsonb_agg(jsonb_build_object('id',x.id,'codigo',x.codigo,'nombre',x.nombre,'categoria',x.categoria,'marca',x.marca,'modelo',x.modelo,'numeroSerie',x.numero_serie,'unidad',x.unidad,'cantidadTotal',x.cantidad_total,'asignado',x.asignado,'noDisponible',x.no_disponible,'disponible',greatest(x.cantidad_total-x.no_disponible,0),'ubicacion',x.ubicacion,'estado',x.estado) order by x.nombre),'[]'::jsonb) into v_activos from (select a.*,coalesce(sum(r.cantidad) filter(where r.estado='asignado'),0) asignado,coalesce(sum(r.cantidad) filter(where r.estado in ('asignado','danado','perdido')),0) no_disponible from public.rh_activos_oficina a left join public.rh_activos_asignaciones r on r.activo_id=a.id group by a.id)x;
    select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'activoId',a.id,'activoCodigo',a.codigo,'activoNombre',a.nombre,'categoria',a.categoria,'marca',a.marca,'modelo',a.modelo,'numeroSerie',a.numero_serie,'unidad',a.unidad,'personalId',p.id,'personalNumero',p.numero_empleado,'personalNombre',btrim(coalesce(p.nombre,'')||' '||coalesce(p.apellidos,'')),'puesto',p.puesto,'departamento',p.departamento,'cantidad',r.cantidad,'fechaAsignacion',r.fecha_asignacion,'fechaDevolucion',r.fecha_devolucion,'estado',r.estado,'condicionEntrega',r.condicion_entrega,'condicionDevolucion',r.condicion_devolucion,'responsableEntrega',r.responsable_entrega,'responsableRecepcion',r.responsable_recepcion) order by r.fecha_asignacion desc,r.id desc),'[]'::jsonb) into v_asignaciones from public.rh_activos_asignaciones r join public.rh_activos_oficina a on a.id=r.activo_id join public.rh_personal p on p.id=r.personal_id;
    return jsonb_build_object('activos',v_activos,'asignaciones',v_asignaciones);
end;
$$;
revoke all on function public.crm_sky_direccion_activos_oficina() from public,anon;
grant execute on function public.crm_sky_direccion_activos_oficina() to authenticated;

insert into public.crm_migraciones(version) values('V46_RH_EQUIPOS_RESguardos_SKY') on conflict(version) do nothing;
notify pgrst,'reload schema';
commit;

select 'OK' estado,(select count(*) from public.rh_activos_oficina) activos_oficina,(select count(*) from public.rh_activos_asignaciones where estado='asignado') resguardos_activos;
