begin;

alter table if exists public.co_proveedores
    add column if not exists whatsapp text;

alter table if exists public.co_solicitudes_proveedor
    add column if not exists proveedor_telefono text,
    add column if not exists proveedor_whatsapp text,
    add column if not exists fecha_envio_correo timestamptz,
    add column if not exists fecha_envio_whatsapp timestamptz,
    add column if not exists error_correo text,
    add column if not exists error_whatsapp text,
    add column if not exists email_message_id text,
    add column if not exists whatsapp_message_id text;

update public.co_solicitudes_proveedor s
set proveedor_telefono=coalesce(nullif(btrim(s.proveedor_telefono),''),p.telefono),
    proveedor_whatsapp=coalesce(nullif(btrim(s.proveedor_whatsapp),''),nullif(btrim(p.whatsapp),''),p.telefono),
    proveedor_email=coalesce(nullif(btrim(s.proveedor_email),''),p.email)
from public.co_proveedores p
where s.proveedor_id=p.id
  and (
    nullif(btrim(s.proveedor_telefono),'') is null or
    nullif(btrim(s.proveedor_whatsapp),'') is null or
    nullif(btrim(s.proveedor_email),'') is null
  );

create table if not exists public.co_comunicaciones_proveedor (
    id bigint generated by default as identity primary key,
    proveedor_id bigint references public.co_proveedores(id) on update cascade on delete set null,
    solicitud_id uuid references public.co_solicitudes_proveedor(id) on update cascade on delete set null,
    canal text not null check (canal in ('email','whatsapp')),
    modo text not null default 'api' check (modo in ('api','manual')),
    destinatario text not null,
    asunto text,
    mensaje text not null,
    estado text not null default 'preparado' check (estado in ('preparado','enviado','error')),
    proveedor_externo_id text,
    error text,
    creado_por uuid references auth.users(id) on delete set null default auth.uid(),
    enviado_at timestamptz,
    created_at timestamptz not null default now()
);

create index if not exists co_comunicaciones_proveedor_proveedor_idx on public.co_comunicaciones_proveedor(proveedor_id,created_at desc);
create index if not exists co_comunicaciones_proveedor_solicitud_idx on public.co_comunicaciones_proveedor(solicitud_id,created_at desc);
create index if not exists co_comunicaciones_proveedor_canal_idx on public.co_comunicaciones_proveedor(canal,created_at desc);

alter table public.co_comunicaciones_proveedor enable row level security;
drop policy if exists "Compras consulta comunicaciones proveedor" on public.co_comunicaciones_proveedor;
create policy "Compras consulta comunicaciones proveedor" on public.co_comunicaciones_proveedor
for select to authenticated
using (
    exists(
        select 1 from public.perfiles_usuario p
        where p.id=auth.uid() and p.activo=true and p.rol in ('administrador','compras')
    )
);
drop policy if exists "Compras administra comunicaciones proveedor" on public.co_comunicaciones_proveedor;
create policy "Compras administra comunicaciones proveedor" on public.co_comunicaciones_proveedor
for all to authenticated
using (
    exists(
        select 1 from public.perfiles_usuario p
        where p.id=auth.uid() and p.activo=true and p.rol in ('administrador','compras')
    )
)
with check (
    exists(
        select 1 from public.perfiles_usuario p
        where p.id=auth.uid() and p.activo=true and p.rol in ('administrador','compras')
    )
);

grant select,insert,update,delete on public.co_comunicaciones_proveedor to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create or replace function public.crm_sky_direccion_compras()
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
    v_proveedores jsonb:='[]'::jsonb;
    v_solicitudes jsonb:='[]'::jsonb;
    v_cotizaciones jsonb:='[]'::jsonb;
    v_solicitudes_proveedor jsonb:='[]'::jsonb;
    v_comunicaciones jsonb:='[]'::jsonb;
    v_material_proveedores jsonb:='[]'::jsonb;
begin
    if not public.crm_es_direccion() then
        raise exception using errcode='42501',message='Esta consulta de Sky está disponible solo para Dirección.';
    end if;

    if to_regclass('public.co_proveedores') is not null then
        select coalesce(jsonb_agg(jsonb_build_object(
            'id',p.id,
            'clave',p.clave,
            'razon_social',p.razon_social,
            'nombre_comercial',p.nombre_comercial,
            'rfc',p.rfc,
            'contacto',p.contacto,
            'email',p.email,
            'telefono',p.telefono,
            'whatsapp',p.whatsapp,
            'categoria',p.categoria,
            'estado',p.estado,
            'tiempo_entrega_dias',p.tiempo_entrega_dias,
            'evaluacion',p.evaluacion
        ) order by p.razon_social),'[]'::jsonb)
        into v_proveedores
        from public.co_proveedores p
        where lower(coalesce(p.estado,'activo'))<>'inactivo';
    end if;

    if to_regclass('public.solicitudes_compra') is not null then
        select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb)
        into v_solicitudes
        from public.solicitudes_compra x;
    end if;

    if to_regclass('public.co_cotizaciones') is not null then
        select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]'::jsonb)
        into v_cotizaciones
        from public.co_cotizaciones x;
    end if;

    if to_regclass('public.co_solicitudes_proveedor') is not null then
        select coalesce(jsonb_agg(jsonb_build_object(
            'id',s.id,
            'numero',s.numero,
            'orden_compra',s.orden_compra,
            'proveedor_nombre',s.proveedor_nombre,
            'proveedor_contacto',s.proveedor_contacto,
            'proveedor_email',s.proveedor_email,
            'proveedor_telefono',s.proveedor_telefono,
            'proveedor_whatsapp',s.proveedor_whatsapp,
            'estado',s.estado,
            'tipo',s.tipo,
            'fecha_envio',s.fecha_envio,
            'fecha_envio_correo',s.fecha_envio_correo,
            'fecha_envio_whatsapp',s.fecha_envio_whatsapp,
            'created_at',s.created_at
        ) order by s.created_at desc),'[]'::jsonb)
        into v_solicitudes_proveedor
        from public.co_solicitudes_proveedor s
        where s.created_at>=now()-interval '180 days';
    end if;

    if to_regclass('public.co_comunicaciones_proveedor') is not null then
        select coalesce(jsonb_agg(jsonb_build_object(
            'canal',c.canal,
            'estado',c.estado,
            'enviado_at',c.enviado_at,
            'created_at',c.created_at
        ) order by c.created_at desc),'[]'::jsonb)
        into v_comunicaciones
        from public.co_comunicaciones_proveedor c
        where c.created_at>=now()-interval '30 days';
    end if;

    if to_regclass('public.co_proveedor_materiales') is not null then
        select coalesce(jsonb_agg(jsonb_build_object(
            'proveedor_id',pm.proveedor_id,
            'proveedor_nombre',coalesce(p.nombre_comercial,p.razon_social),
            'proveedor_contacto',p.contacto,
            'proveedor_email',p.email,
            'proveedor_telefono',p.telefono,
            'proveedor_whatsapp',p.whatsapp,
            'proveedor_rfc',p.rfc,
            'material_codigo',pm.material_codigo,
            'descripcion',coalesce(pm.descripcion,m.descripcion),
            'marca',coalesce(pm.marca,m.marca),
            'categoria',m.categoria,
            'unidad',m.unidad,
            'precio_unitario',pm.precio_unitario,
            'moneda',pm.moneda,
            'plazo_entrega_dias',pm.plazo_entrega_dias,
            'cantidad_minima',pm.cantidad_minima,
            'vigencia_hasta',pm.vigencia_hasta
        ) order by coalesce(p.nombre_comercial,p.razon_social),pm.material_codigo),'[]'::jsonb)
        into v_material_proveedores
        from public.co_proveedor_materiales pm
        join public.co_proveedores p on p.id=pm.proveedor_id
        left join public.materiales m on m.codigo=pm.material_codigo
        where coalesce(pm.activo,true)=true
          and lower(coalesce(p.estado,'activo'))<>'inactivo';
    end if;

    return jsonb_build_object(
        'proveedores',v_proveedores,
        'solicitudes',v_solicitudes,
        'cotizaciones',v_cotizaciones,
        'solicitudes_proveedor',v_solicitudes_proveedor,
        'comunicaciones',v_comunicaciones,
        'material_proveedores',v_material_proveedores
    );
end;
$$;

revoke all on function public.crm_sky_direccion_compras() from public,anon;
grant execute on function public.crm_sky_direccion_compras() to authenticated;

insert into public.crm_migraciones(version,aplicada_at)
values('CRM-V45-COMPRAS-BUSCADORES-SKY-2026-08-11',now())
on conflict(version) do update set aplicada_at=excluded.aplicada_at;

notify pgrst,'reload schema';
commit;

select
    case when exists(
        select 1 from information_schema.columns
        where table_schema='public' and table_name='co_proveedores' and column_name='whatsapp'
    ) then 'OK' else 'FALTA' end as whatsapp_proveedores,
    case when to_regclass('public.co_comunicaciones_proveedor') is not null then 'OK' else 'FALTA' end as historial_comunicaciones,
    case when exists(
        select 1 from information_schema.columns
        where table_schema='public' and table_name='co_solicitudes_proveedor' and column_name='proveedor_whatsapp'
    ) then 'OK' else 'FALTA' end as whatsapp_solicitudes,
    case when to_regprocedure('public.crm_sky_direccion_compras()') is not null then 'OK' else 'FALTA' end as sky_compras_direccion;
