begin;

create table if not exists public.proyecto_servicios(
    id bigint generated by default as identity primary key,
    proyecto_numero text not null references public.proyectos(numero_proyecto) on update cascade on delete cascade,
    activo_tipo text not null,
    activo_id bigint,
    activo_codigo text,
    activo_nombre text not null,
    activo_detalle text,
    tipo_servicio text not null,
    fecha_servicio date not null default current_date,
    estado text not null default 'completado',
    responsable text,
    proveedor text,
    referencia text,
    costo numeric(14,2) not null default 0,
    moneda text not null default 'MXN',
    descripcion text not null,
    proximo_servicio date,
    notas text,
    creado_por uuid references auth.users(id) on delete set null default auth.uid(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.proyecto_servicios drop constraint if exists proyecto_servicios_activo_tipo_check;
alter table public.proyecto_servicios add constraint proyecto_servicios_activo_tipo_check check(activo_tipo in ('equipo_oficina','vehiculo','herramienta'));
alter table public.proyecto_servicios drop constraint if exists proyecto_servicios_tipo_servicio_check;
alter table public.proyecto_servicios add constraint proyecto_servicios_tipo_servicio_check check(tipo_servicio in ('mantenimiento_preventivo','mantenimiento_correctivo','reparacion','inspeccion','calibracion','limpieza','diagnostico','otro'));
alter table public.proyecto_servicios drop constraint if exists proyecto_servicios_estado_check;
alter table public.proyecto_servicios add constraint proyecto_servicios_estado_check check(estado in ('programado','pendiente','en_proceso','completado','cancelado'));
alter table public.proyecto_servicios drop constraint if exists proyecto_servicios_moneda_check;
alter table public.proyecto_servicios add constraint proyecto_servicios_moneda_check check(moneda in ('MXN','USD','EUR'));
alter table public.proyecto_servicios drop constraint if exists proyecto_servicios_costo_check;
alter table public.proyecto_servicios add constraint proyecto_servicios_costo_check check(costo>=0);

create index if not exists proyecto_servicios_proyecto_fecha_idx on public.proyecto_servicios(proyecto_numero,fecha_servicio desc,id desc);
create index if not exists proyecto_servicios_activo_idx on public.proyecto_servicios(activo_tipo,activo_id);
create index if not exists proyecto_servicios_estado_idx on public.proyecto_servicios(proyecto_numero,estado);
create index if not exists proyecto_servicios_proximo_idx on public.proyecto_servicios(proximo_servicio) where proximo_servicio is not null;

create or replace function public.proyecto_servicios_actualizar_fecha()
returns trigger
language plpgsql
set search_path=public
as $$
begin
    new.updated_at=now();
    return new;
end;
$$;

drop trigger if exists trg_proyecto_servicios_actualizar_fecha on public.proyecto_servicios;
create trigger trg_proyecto_servicios_actualizar_fecha before update on public.proyecto_servicios for each row execute function public.proyecto_servicios_actualizar_fecha();

alter table public.proyecto_servicios enable row level security;
drop policy if exists proyecto_servicios_lectura on public.proyecto_servicios;
drop policy if exists proyecto_servicios_escritura on public.proyecto_servicios;
create policy proyecto_servicios_lectura on public.proyecto_servicios for select to authenticated using(public.crm_usuario_tiene_rol(array['administrador','jefe_almacen','almacen','compras','proyectos','rh','finanzas','gerente_general','subgerente']));
create policy proyecto_servicios_escritura on public.proyecto_servicios for all to authenticated using(public.crm_usuario_tiene_rol(array['administrador','jefe_almacen','almacen','compras','proyectos','rh','gerente_general','subgerente'])) with check(public.crm_usuario_tiene_rol(array['administrador','jefe_almacen','almacen','compras','proyectos','rh','gerente_general','subgerente']));

revoke all on public.proyecto_servicios from anon;
grant select,insert,update,delete on public.proyecto_servicios to authenticated;
grant usage,select on sequence public.proyecto_servicios_id_seq to authenticated;

create or replace function public.proyecto_servicios_listar_activos()
returns table(tipo_activo text,activo_id bigint,codigo text,nombre text,detalle text,estado text)
language plpgsql
security definer
set search_path=public,pg_catalog
as $$
begin
    if auth.uid() is null or not public.crm_usuario_tiene_rol(array['administrador','jefe_almacen','almacen','compras','proyectos','rh','finanzas','gerente_general','subgerente']) then
        raise exception using errcode='42501',message='Tu perfil no tiene permiso para consultar activos de servicios.';
    end if;
    return query
    select 'equipo_oficina'::text,a.id,a.codigo,a.nombre,concat_ws(' · ',nullif(a.categoria,''),nullif(a.marca,''),nullif(a.modelo,''),nullif(a.numero_serie,''),nullif(a.ubicacion,''))::text,a.estado::text
    from public.rh_activos_oficina a
    where coalesce(a.estado,'activo')<>'baja'
    union all
    select 'vehiculo'::text,v.id,v.numero_economico,concat_ws(' ',nullif(v.marca,''),nullif(v.modelo,''))::text,concat_ws(' · ',nullif(v.placas,''),nullif(v.tipo,''),case when v.anio is null then null else v.anio::text end,nullif(v.color,''))::text,v.estado::text
    from public.vehiculos v
    where coalesce(v.activo,true)=true
    union all
    select 'herramienta'::text,u.id,coalesce(nullif(u.codigo_interno,''),nullif(h.sku,''),u.id::text)::text,h.descripcion::text,concat_ws(' · ',nullif(h.clasificacion,''),nullif(h.marca,''),nullif(h.modelo,''),nullif(u.proyecto,''))::text,u.estado::text
    from public.herramientas_unidades u
    join public.herramientas_catalogo h on h.id=u.herramienta_id
    where coalesce(h.activo,true)=true;
end;
$$;

revoke all on function public.proyecto_servicios_listar_activos() from public,anon;
grant execute on function public.proyecto_servicios_listar_activos() to authenticated,service_role;

notify pgrst,'reload schema';

commit;
